import type { ReferenceSlotId, SceneAspectRatio } from "./types";

export type SceneOption = {
  /** Stored value (label). Keep as the source-of-truth so buildPrompt stays simple. */
  value: string;
  /** Short Japanese hint shown under the label. */
  hint?: string;
  /** Visual cue category. UI renders a glyph based on this. */
  visual:
    | "frame-close"
    | "frame-medium"
    | "frame-wide"
    | "frame-aerial"
    | "frame-tilt"
    | "frame-shoulder"
    | "aspect"
    | "light-natural"
    | "light-studio"
    | "light-back"
    | "light-blue-hour"
    | "light-candle"
    | "light-softbox"
    | "camera-film"
    | "camera-digital"
    | "camera-retro"
    | "camera-cinema"
    | "camera-mobile"
    | "focal"
    | "lens"
    | "film-stock"
    | "style"
    | "filter"
    | "none";
  /** Optional thumbnail to show inside the card. Generated by
   *  scripts/generate-scene-thumbnails.sh and placed in
   *  /scene-thumbnails/<category>/<slug>.png. */
  thumbnail?: { src: string; alt: string };
  /** Optional preview video (loop). Placed in /scene-videos/<slug>.webm.
   *  動き・カメラ系の選択肢でホバー時に再生し、動きを直感的に見せる。
   *  一覧では読まず (preload="none")、ホバーした1本だけ再生する。 */
  video?: string;
  /**
   * Optional English prompt fragment. When present, buildPrompt outputs
   * this string verbatim instead of the raw `value`. Used by the unified
   * "style" axis where each preset includes look + grading + finish in
   * one completed phrase, so the user does not have to combine 3 fields.
   */
  prompt?: string;
};

function thumb(category: string, slug: string, alt: string): { src: string; alt: string } {
  return { src: `/scene-thumbnails/${category}/${slug}.png`, alt };
}

/** Sentinel value meaning "do not include in the prompt". buildPrompt skips
 *  any option whose value equals this. */
export const NO_SELECT = "No select";

/** Shared "No select" option placed at the head of every list. The
 *  UI renders a CSS placeholder for options without a `thumbnail`,
 *  so we don't need an image asset for this case. */
const NO_SELECT_OPTION: SceneOption = {
  value: NO_SELECT,
  hint: "指定なし",
  visual: "none",
};

export const compositionOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  { value: "Close Up", hint: "顔・ディテール", visual: "frame-close", thumbnail: thumb("composition", "close-up", "Close Up") },
  { value: "Medium", hint: "胸から上", visual: "frame-medium", thumbnail: thumb("composition", "medium", "Medium") },
  { value: "Wide", hint: "全身・引き", visual: "frame-wide", thumbnail: thumb("composition", "wide", "Wide") },
  { value: "Bird's-eye", hint: "真上から", visual: "frame-aerial", thumbnail: thumb("composition", "birds-eye", "Bird's-eye") },
  { value: "Dutch Angle", hint: "斜めの傾き", visual: "frame-tilt", thumbnail: thumb("composition", "dutch-angle", "Dutch Angle") },
  { value: "Over-the-shoulder", hint: "肩越し", visual: "frame-shoulder", thumbnail: thumb("composition", "over-the-shoulder", "Over-the-shoulder") },
];

// STΛCK 指示 (2026-06-09): GPT Image 2 公式対応比率から撮影用途を厚く (5:4 / 3:4 追加)。
// 横長 (シネスコ → TV → 物撮り) → 正方 → 縦長 (Instagram → ポートレート → Reels) の対称な並び。
// すべて公式制約 (1:3〜3:1, 両辺16の倍数) 内。詳細は scene/types.ts のコメント参照。
export const aspectRatioOptions: SceneAspectRatio[] = [
  "21:9",
  "16:9",
  "3:2",
  "4:3",
  "5:4",
  "1:1",
  "4:5",
  "3:4",
  "2:3",
  "9:16",
];

export const lightSourceOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  { value: "自然光", hint: "屋外・窓辺", visual: "light-natural", thumbnail: thumb("light_source", "natural-light", "自然光") },
  { value: "スタジオ", hint: "均一光・撮影所", visual: "light-studio", thumbnail: thumb("light_source", "studio", "スタジオ") },
  { value: "逆光", hint: "後ろから差す光", visual: "light-back", thumbnail: thumb("light_source", "backlight", "逆光") },
  { value: "Blue Hour", hint: "夕暮れの青い時間", visual: "light-blue-hour", thumbnail: thumb("light_source", "blue-hour", "Blue Hour") },
  { value: "Candlelight", hint: "ろうそくの暖色", visual: "light-candle", thumbnail: thumb("light_source", "candlelight", "Candlelight") },
  { value: "Softbox", hint: "拡散柔光", visual: "light-softbox", thumbnail: thumb("light_source", "softbox", "Softbox") },
];

/**
 * カメラ機材。質感を決める軸として残す（5 個に絞った）。
 * VHS / iPhone Pro はローファイ・モバイル感が画像にも出やすい。
 * 「フィルム」単独はスタイルの粒子表現と被るので削除。
 */
export const cameraEquipmentOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  {
    value: "シネマカメラ",
    hint: "FX6・Alexa 等",
    visual: "camera-cinema",
    thumbnail: thumb("camera_equipment", "arri-alexa-mini", "シネマカメラ"),
    prompt: "modern cinema camera, high dynamic range, professional cinematography",
  },
  {
    value: "デジタル一眼",
    hint: "クリーン・高解像",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "digital-camera", "デジタル一眼"),
    prompt: "digital DSLR camera, clean sharp resolution",
  },
  {
    value: "フィルムカメラ",
    hint: "粒状・温かみ",
    visual: "camera-film",
    thumbnail: thumb("camera_equipment", "film-camera", "フィルムカメラ"),
    prompt: "shot on film, organic grain, warm color reproduction",
  },
  {
    value: "スマホ",
    hint: "即時性・自然",
    visual: "camera-mobile",
    thumbnail: thumb("camera_equipment", "iphone-pro", "スマホ"),
    prompt: "smartphone camera, casual immediate look, natural everyday framing",
  },
  {
    value: "VHS",
    hint: "ローファイ・90年代",
    visual: "camera-retro",
    thumbnail: thumb("camera_equipment", "vhs", "VHS"),
    prompt: "vintage VHS recording, lo-fi 90s aesthetic, scan lines, soft tape texture",
  },
];

/**
 * ショット幅（旧 焦点距離 + レンズ を統合）。
 *
 * 元は焦点距離（mm 数値） と レンズ種類（魚眼/望遠 等）が別軸で、
 * 「8mm = 魚眼」「200mm = 望遠」が両軸に重複していた。
 * 中級プロでも数値より「効果名」で選ぶ方が早いため 1 軸に統合。
 *
 * value は日本語ラベル（中級プロが読みやすい）、prompt は英語完成形。
 */
export const shotOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  {
    value: "超広角・魚眼",
    hint: "歪み・没入感（8mm）",
    visual: "focal",
    thumbnail: thumb("focal_length", "8mm", "超広角・魚眼"),
    prompt: "ultra-wide-angle fisheye lens, immersive distortion",
  },
  {
    value: "広角",
    hint: "風景・空間（35mm）",
    visual: "focal",
    thumbnail: thumb("focal_length", "35mm", "広角"),
    prompt: "35mm wide-angle lens, generous environmental framing",
  },
  {
    value: "標準",
    hint: "人の視点（50mm）",
    visual: "focal",
    thumbnail: thumb("focal_length", "50mm", "標準"),
    prompt: "50mm standard lens, natural human-eye perspective",
  },
  {
    value: "ポートレート",
    hint: "人物・浅い被写界深度（85mm）",
    visual: "focal",
    thumbnail: thumb("focal_length", "85mm", "ポートレート"),
    prompt: "85mm portrait lens, shallow depth of field, creamy background bokeh",
  },
  {
    value: "望遠",
    hint: "圧縮・遠景（200mm）",
    visual: "focal",
    thumbnail: thumb("focal_length", "200mm", "望遠"),
    prompt: "200mm telephoto lens, compressed perspective, isolated subject",
  },
  {
    value: "マクロ接写",
    hint: "ディテール・質感",
    visual: "lens",
    thumbnail: thumb("lens", "macro", "マクロ接写"),
    prompt: "macro close-up, extreme detail and texture",
  },
  {
    value: "ティルトシフト",
    hint: "ミニチュア感",
    visual: "lens",
    thumbnail: thumb("lens", "tilt-shift", "ティルトシフト"),
    prompt: "tilt-shift miniature effect, selective focal plane",
  },
  {
    value: "アナモルフィック",
    hint: "シネマ横長ボケ",
    visual: "lens",
    thumbnail: thumb("lens", "anamorphic", "アナモルフィック"),
    prompt: "anamorphic lens, oval bokeh, cinematic widescreen flare",
  },
];

// filmOptions は削除済み。フィルム種類（Cinestill/Kodak/Fuji 等）は
// スタイル軸に内包される（例: ストリート粒子 / モノクロストリート / ネオノワール）。
// ここに再追加せず、必要ならスタイル新設で対応する。

/**
 * 統合スタイル軸。1 個選ぶだけで「ジャンル + 色味 + 質感」が完成形で
 * プロンプトに乗る。旧 photographerStyle / cinematicLook / filter を統合。
 *
 * Why: ユーザー視点で「結局どれを選べば絵の雰囲気が決まるのか」が分かりにくい
 * ため、3 軸を 1 軸に畳む。微調整したい上級者は promptOverride で
 * 英語プロンプトを直接編集できる。
 *
 * thumbnail は既存資産（cinematic_look / photographer の生成済み 11 枚）を
 * リネーム移動なしで参照する。新スタイルの新規サムネは段階的に差し替える。
 */
export const styleOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  {
    value: "ドキュメンタリーリアリズム",
    hint: "誠実・自然・報道写真",
    visual: "style",
    thumbnail: thumb("cinematic_look", "documentary-realism", "ドキュメンタリーリアリズム"),
    prompt: "documentary realism, naturalistic light, photojournalism feel, subtle grain",
  },
  {
    value: "ネオノワール",
    hint: "暗闇・ネオン・影",
    visual: "style",
    thumbnail: thumb("cinematic_look", "neo-noir", "ネオノワール"),
    prompt: "neo-noir, low-key lighting, deep shadows, neon accents, high contrast, subtle halation",
  },
  {
    value: "パステル昼光",
    hint: "柔らかな昼光・夢見心地",
    visual: "style",
    thumbnail: thumb("cinematic_look", "pastel-daylight", "パステル昼光"),
    prompt: "pastel daylight palette, soft natural light, airy cinematic mood, light film grain",
  },
  {
    value: "ハイコントラスト劇的",
    hint: "強い陰影・キアロスクーロ",
    visual: "style",
    thumbnail: thumb("cinematic_look", "high-contrast", "ハイコントラスト劇的"),
    prompt: "high-contrast cinematic lighting, dramatic chiaroscuro, deep blacks, controlled highlights",
  },
  {
    value: "ミュートドラマ",
    hint: "彩度抑え・絵画的",
    visual: "style",
    thumbnail: thumb("cinematic_look", "muted-drama", "ミュートドラマ"),
    prompt: "muted dramatic palette, desaturated grading, painterly atmosphere, classical composition",
  },
  {
    value: "クリーンコマーシャル",
    hint: "明るく整った商業",
    visual: "style",
    thumbnail: thumb("cinematic_look", "clean-commercial", "クリーンコマーシャル"),
    prompt: "clean commercial photography, bright even lighting, polished editorial finish",
  },
  {
    value: "エディトリアルポートレート",
    hint: "雑誌風・人物中心",
    visual: "style",
    thumbnail: thumb("photographer", "annie-leibovitz", "エディトリアルポートレート"),
    prompt: "editorial portrait, magazine cover quality, environmental context, controlled drama",
  },
  {
    value: "アメリカーナ叙情",
    hint: "アメリカ的・物語性",
    visual: "style",
    thumbnail: thumb("photographer", "alec-soth", "アメリカーナ叙情"),
    prompt: "narrative americana documentary photography, quiet observation, poetic atmosphere",
  },
  {
    value: "大判建築",
    hint: "建築・厳密・大判",
    visual: "style",
    thumbnail: thumb("photographer", "andreas-gursky", "大判建築"),
    prompt: "large-format architectural photography, monumental scale, hyper-detailed precision",
  },
  {
    value: "ストリート粒子",
    hint: "街・粒子感・モノクロ寄り",
    visual: "style",
    thumbnail: thumb("photographer", "daido-moriyama", "ストリート粒子"),
    prompt: "high-contrast street photography with heavy grain, gritty urban observation",
  },
  {
    value: "モノクロストリート",
    hint: "白黒・候補的瞬間",
    visual: "style",
    thumbnail: thumb("photographer", "vivian-maier", "モノクロストリート"),
    prompt: "classic black-and-white street photography, decisive moment, subtle film grain",
  },
];

export const referenceSlotIds: ReferenceSlotId[] = [
  "@img1",
  "@img2",
  "@img3",
  "@img4",
  "@img5",
];
