import type { ReferenceSlotId, SceneAspectRatio } from "./types";

/**
 * 構図の役割グループ。UI で「どこに何を入れればいいか」を分かるようにするための見出し。
 *
 * なぜ追加したか (2026-07-27):
 *   STΛCK から「構図とカメラで選択が分かれていて、どこに何を入れればいいか分からない」
 *   と指摘された。実際に見ると (a)「ショット幅」がカメラの中にあり、(b) 構図の中にも
 *   Close Up / Full Shot など写る範囲の指定が混ざっていて、**同じことを決める場所が
 *   2箇所に分かれていた**。
 *
 *   保存されるデータ構造は変えず (subjectFraming.composition と camera.focalLength の
 *   ままにする)、表示だけを役割ごとに束ねる。過去のプリセットを壊さずに分かりやすさだけ
 *   を上げるため。
 */
export type CompositionGroup =
  /** どこまで写すか (被写体との距離)。極寄り→全身→引き の段階 */
  | "distance"
  /** どこから撮るか (カメラの位置・角度・被写体の向き) */
  | "angle"
  /** どう見せるか (画面内の配置・遮蔽・反射などの演出) */
  | "framing";

export const COMPOSITION_GROUP_LABELS: Record<CompositionGroup, { title: string; hint: string }> = {
  distance: { title: "どこまで写す", hint: "被写体にどこまで寄るか" },
  angle: { title: "どこから撮る", hint: "カメラの高さ・角度・向き" },
  framing: { title: "どう見せる", hint: "画面のどこに置くか・何で遮るか" },
};


export type SceneOption = {
  /** Stored value (label). Keep as the source-of-truth so buildPrompt stays simple. */
  value: string;
  /** 構図の役割グループ。compositionOptions のみ使う。UI のグループ見出しになる。 */
  group?: CompositionGroup;
  /** Short Japanese hint shown under the label. */
  hint?: string;
  /** Visual cue category. UI renders a glyph based on this. */
  visual:
    | "frame-close"
    | "frame-medium"
    | "frame-wide"
    | "frame-aerial"
    | "frame-tilt"
    | "frame-shoulder"
    | "aspect"
    | "light-natural"
    | "light-studio"
    | "light-back"
    | "light-blue-hour"
    | "light-candle"
    | "light-softbox"
    | "camera-film"
    | "camera-digital"
    | "camera-retro"
    | "camera-cinema"
    | "camera-mobile"
    | "focal"
    | "lens"
    | "film-stock"
    | "style"
    | "filter"
    | "none";
  /** Optional thumbnail to show inside the card. Generated by
   *  scripts/generate-scene-thumbnails.sh and placed in
   *  /scene-thumbnails/<category>/<slug>.png. */
  thumbnail?: { src: string; alt: string };
  /** Optional preview video (loop). Placed in /scene-videos/<slug>.webm.
   *  動き・カメラ系の選択肢でホバー時に再生し、動きを直感的に見せる。
   *  一覧では読まず (preload="none")、ホバーした1本だけ再生する。 */
  video?: string;
  /**
   * Optional English prompt fragment. When present, buildPrompt outputs
   * this string verbatim instead of the raw `value`. Used by the unified
   * "style" axis where each preset includes look + grading + finish in
   * one completed phrase, so the user does not have to combine 3 fields.
   */
  prompt?: string;
};

function thumb(category: string, slug: string, alt: string): { src: string; alt: string } {
  return { src: `/scene-thumbnails/${category}/${slug}.png`, alt };
}

/** Sentinel value meaning "do not include in the prompt". buildPrompt skips
 *  any option whose value equals this. */
export const NO_SELECT = "No select";

/** Shared "No select" option placed at the head of every list. The
 *  UI renders a CSS placeholder for options without a `thumbnail`,
 *  so we don't need an image asset for this case. */
const NO_SELECT_OPTION: SceneOption = {
  value: NO_SELECT,
  hint: "指定なし",
  visual: "none",
};

export const compositionOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  {
    value: "Extreme Close Up",
    group: "distance",
    hint: "部分の極寄り",
    visual: "frame-close",
    thumbnail: thumb("composition", "extreme-close-up", "Extreme Close Up"),
  },
  {
    value: "Close Up",
    group: "distance",
    hint: "頭部から肩まで",
    visual: "frame-close",
    thumbnail: thumb("composition", "close-up", "Close Up"),
  },
  {
    value: "Bust Shot",
    group: "distance",
    hint: "胸上・証明写真",
    visual: "frame-close",
    thumbnail: thumb("composition", "bust-shot", "Bust Shot"),
  },
  {
    value: "Medium",
    group: "distance",
    hint: "腰から上",
    visual: "frame-medium",
    thumbnail: thumb("composition", "medium", "Medium"),
  },
  {
    value: "Cowboy Shot",
    group: "distance",
    hint: "膝上・腿まで",
    visual: "frame-medium",
    thumbnail: thumb("composition", "cowboy-shot", "Cowboy Shot"),
  },
  {
    value: "Full Shot",
    group: "distance",
    hint: "全身ぴったり",
    visual: "frame-wide",
    thumbnail: thumb("composition", "full-shot", "Full Shot"),
  },
  {
    value: "Wide",
    group: "distance",
    hint: "全身・空間に余白",
    visual: "frame-wide",
    thumbnail: thumb("composition", "wide", "Wide"),
  },
  {
    value: "Bird's-eye",
    group: "angle",
    hint: "真上から見下ろす",
    visual: "frame-aerial",
    thumbnail: thumb("composition", "birds-eye", "Bird's-eye"),
  },
  {
    value: "High Angle",
    group: "angle",
    hint: "やや上から見下ろす",
    visual: "frame-medium",
    thumbnail: thumb("composition", "high-angle", "High Angle"),
  },
  {
    value: "Eye Level Straight",
    group: "angle",
    hint: "目線の高さ・基準",
    visual: "frame-medium",
    thumbnail: thumb("composition", "eye-level-straight", "Eye Level Straight"),
  },
  {
    value: "Low Angle",
    group: "angle",
    hint: "下から見上げる",
    visual: "frame-medium",
    thumbnail: thumb("composition", "low-angle", "Low Angle"),
  },
  {
    value: "Worm's-eye",
    group: "angle",
    hint: "床から極端に見上げる",
    visual: "frame-medium",
    thumbnail: thumb("composition", "worms-eye", "Worm's-eye"),
  },
  {
    value: "Dutch Angle",
    group: "angle",
    hint: "カメラを傾ける",
    visual: "frame-tilt",
    thumbnail: thumb("composition", "dutch-angle", "Dutch Angle"),
  },
  {
    value: "Three-Quarter View",
    group: "angle",
    hint: "斜め45度から",
    visual: "frame-medium",
    thumbnail: thumb("composition", "three-quarter-view", "Three-Quarter View"),
  },
  {
    value: "Profile View",
    group: "angle",
    hint: "真横から",
    visual: "frame-medium",
    thumbnail: thumb("composition", "profile-view", "Profile View"),
  },
  {
    value: "Back View",
    group: "angle",
    hint: "真後ろから",
    visual: "frame-medium",
    thumbnail: thumb("composition", "back-view", "Back View"),
  },
  {
    value: "Rule of Thirds Left",
    group: "framing",
    hint: "左三分割に寄せる",
    visual: "frame-medium",
    thumbnail: thumb("composition", "rule-of-thirds-left", "Rule of Thirds Left"),
  },
  {
    value: "Rule of Thirds Right",
    group: "framing",
    hint: "右三分割に寄せる",
    visual: "frame-medium",
    thumbnail: thumb("composition", "rule-of-thirds-right", "Rule of Thirds Right"),
  },
  {
    value: "Negative Space Top",
    group: "framing",
    hint: "上部を大きく空ける",
    visual: "frame-aerial",
    thumbnail: thumb("composition", "negative-space-top", "Negative Space Top"),
  },
  {
    value: "Symmetrical Center",
    group: "framing",
    hint: "完全中央・左右対称",
    visual: "frame-medium",
    thumbnail: thumb("composition", "symmetrical-center", "Symmetrical Center"),
  },
  {
    value: "Edge Crop",
    group: "framing",
    hint: "画面端で断ち切る",
    visual: "frame-medium",
    thumbnail: thumb("composition", "edge-crop", "Edge Crop"),
  },
  {
    value: "Floor Level Long Lens",
    group: "angle",
    hint: "床すれすれの水平",
    visual: "frame-medium",
    thumbnail: thumb("composition", "floor-level-long-lens", "Floor Level Long Lens"),
  },
  {
    value: "Over-the-shoulder",
    group: "angle",
    hint: "肩越しに見る視点",
    visual: "frame-shoulder",
    thumbnail: thumb("composition", "over-the-shoulder", "Over-the-shoulder"),
  },

  // ── 特殊構図 (2026-07-27 追加) ──────────────────────────────
  //
  // なぜ足したか: 既存23件は三分割・見上げ・肩越しといった撮影入門書の基本形ばかりで、
  // STΛCK から「もっと特殊な、海外の広告/MVで見るような構図がないのか」と指摘された。
  // 基本形は実務で最も使うので残し、その上に「見たことがない側」を積む。
  //
  // 分類の軸は3つ: (1)空間の使い方が特殊 (2)カメラの物理位置が特殊 (3)関係性・演出が特殊。
  {
    value: "Frame in Frame",
    group: "framing",
    hint: "ドア枠や窓の中に収める",
    visual: "frame-shoulder",
    thumbnail: thumb("composition", "frame-in-frame", "Frame in Frame"),
  },
  {
    value: "Foreground Occlusion",
    group: "framing",
    hint: "手前を遮って覗き見る",
    visual: "frame-shoulder",
    thumbnail: thumb("composition", "foreground-occlusion", "Foreground Occlusion"),
  },
  {
    value: "Reflection Subject",
    group: "framing",
    hint: "水たまりや窓の映り込みが主役",
    visual: "frame-shoulder",
    thumbnail: thumb("composition", "reflection-subject", "Reflection Subject"),
  },
  {
    value: "Extreme Negative Space",
    group: "framing",
    hint: "9割が空白・人は隅に小さく",
    visual: "frame-aerial",
    thumbnail: thumb("composition", "extreme-negative-space", "Extreme Negative Space"),
  },
  {
    value: "God's-eye Flat",
    group: "angle",
    hint: "真上から・奥行きを完全に消す",
    visual: "frame-aerial",
    thumbnail: thumb("composition", "gods-eye-flat", "God's-eye Flat"),
  },
  {
    value: "Ground Crawl",
    group: "angle",
    hint: "路面が巨大・這うような視点",
    visual: "frame-tilt",
    thumbnail: thumb("composition", "ground-crawl", "Ground Crawl"),
  },
  {
    value: "POV Behind",
    group: "angle",
    hint: "後頭部越しに見える世界",
    visual: "frame-shoulder",
    thumbnail: thumb("composition", "pov-behind", "POV Behind"),
  },
  {
    value: "Deep Focus Two-Plane",
    group: "framing",
    hint: "手前も奥も両方くっきり",
    visual: "frame-shoulder",
    thumbnail: thumb("composition", "deep-focus-two-plane", "Deep Focus Two-Plane"),
  },
  {
    value: "Overhead Hands",
    group: "framing",
    hint: "手だけを真上から平面的に",
    visual: "frame-aerial",
    thumbnail: thumb("composition", "overhead-hands", "Overhead Hands"),
  },
  {
    value: "Silhouette Only",
    group: "framing",
    hint: "逆光で真っ黒・形だけで見せる",
    visual: "frame-shoulder",
    thumbnail: thumb("composition", "silhouette-only", "Silhouette Only"),
  },
  {
    value: "Dutch Low Wide",
    group: "angle",
    hint: "歪み+傾き+見上げの全部乗せ",
    visual: "frame-tilt",
    thumbnail: thumb("composition", "dutch-low-wide", "Dutch Low Wide"),
  },
];

// STΛCK 指示 (2026-06-09): GPT Image 2 公式対応比率から撮影用途を厚く (5:4 / 3:4 追加)。
// 横長 (シネスコ → TV → 物撮り) → 正方 → 縦長 (Instagram → ポートレート → Reels) の対称な並び。
// すべて公式制約 (1:3〜3:1, 両辺16の倍数) 内。詳細は scene/types.ts のコメント参照。
export const aspectRatioOptions: SceneAspectRatio[] = [
  "21:9",
  "16:9",
  "3:2",
  "4:3",
  "5:4",
  "1:1",
  "4:5",
  "3:4",
  "2:3",
  "9:16",
];

export const lightSourceOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  {
    value: "スタジオ",
    hint: "均一光・影ほぼ無し",
    visual: "light-studio",
    thumbnail: thumb("light_source", "studio", "スタジオ"),
  },
  {
    value: "Softbox",
    hint: "拡散柔光・影が柔らかい",
    visual: "light-softbox",
    thumbnail: thumb("light_source", "softbox", "Softbox"),
  },
  {
    value: "逆光",
    hint: "後ろから差す光",
    visual: "light-back",
    thumbnail: thumb("light_source", "backlight", "逆光"),
  },
  {
    value: "Front Flat",
    hint: "正面から平坦に",
    visual: "light-studio",
    thumbnail: thumb("light_source", "front-flat", "Front Flat"),
  },
  {
    value: "Side Light",
    hint: "真横から・半分陰",
    visual: "light-studio",
    thumbnail: thumb("light_source", "side-light", "Side Light"),
  },
  {
    value: "Rim Light",
    hint: "輪郭だけ光る",
    visual: "light-back",
    thumbnail: thumb("light_source", "rim-light", "Rim Light"),
  },
  {
    value: "Top Light",
    hint: "真上から落ちる光",
    visual: "light-studio",
    thumbnail: thumb("light_source", "top-light", "Top Light"),
  },
  {
    value: "Under Light",
    hint: "真下から上向き",
    visual: "light-studio",
    thumbnail: thumb("light_source", "under-light", "Under Light"),
  },
  {
    value: "Hard Direct",
    hint: "硬い直射・輪郭鋭い",
    visual: "light-studio",
    thumbnail: thumb("light_source", "hard-direct", "Hard Direct"),
  },
  {
    value: "自然光",
    hint: "屋外・窓辺の昼光",
    visual: "light-natural",
    thumbnail: thumb("light_source", "natural-light", "自然光"),
  },
  {
    value: "Golden Hour",
    hint: "低い太陽・強い暖色",
    visual: "light-studio",
    thumbnail: thumb("light_source", "golden-hour", "Golden Hour"),
  },
  {
    value: "Blue Hour",
    hint: "日没後の青い時間",
    visual: "light-blue-hour",
    thumbnail: thumb("light_source", "blue-hour", "Blue Hour"),
  },
  {
    value: "Candlelight",
    hint: "ろうそく・弱い暖色点光源",
    visual: "light-candle",
    thumbnail: thumb("light_source", "candlelight", "Candlelight"),
  },
  {
    value: "ネオン管",
    hint: "実在ネオン管が唯一の光源",
    visual: "light-studio",
    thumbnail: thumb("light_source", "neon-tube", "ネオン管"),
  },
  {
    value: "Overcast",
    hint: "曇天・全方向から均一",
    visual: "light-natural",
    thumbnail: thumb("light_source", "overcast", "Overcast"),
  },
];

/**
 * カメラ機材。質感を決める軸として残す（5 個に絞った）。
 * VHS / iPhone Pro はローファイ・モバイル感が画像にも出やすい。
 * 「フィルム」単独はスタイルの粒子表現と被るので削除。
 */
export const cameraEquipmentOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  {
    value: "スマホ",
    hint: "気軽・全体にピント",
    visual: "camera-mobile",
    thumbnail: thumb("camera_equipment", "iphone-pro", "スマホ"),
    prompt:
      "shot on a smartphone camera, wide near-pan-focus depth of field, casual immediate everyday framing, sharp computational HDR detail",
  },
  {
    value: "APS-Cミラーレス",
    hint: "軽装備・少し深め",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "aps-c-mirrorless", "APS-Cミラーレス"),
    prompt:
      "shot on an APS-C mirrorless camera, moderate depth of field with the background softly separated but still readable, crisp lightweight documentary look",
  },
  {
    value: "フルフレームミラーレス",
    hint: "背景がとろける定番",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "full-frame-mirrorless", "フルフレームミラーレス"),
    prompt:
      "shot on a full-frame mirrorless camera with a fast prime lens, shallow depth of field, creamy rounded bokeh, clean modern color separation",
  },
  {
    value: "デジタル一眼",
    hint: "クリーン・高解像",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "digital-camera", "デジタル一眼"),
    prompt:
      "shot on a digital DSLR, clean sharp resolution, controlled dynamic range, medium depth of field with a naturally soft background",
  },
  {
    value: "シネマカメラ",
    hint: "映画の質感・浅い",
    visual: "camera-cinema",
    thumbnail: thumb("camera_equipment", "arri-alexa-mini", "シネマカメラ"),
    prompt:
      "shot on a digital cinema camera, high dynamic range, gentle highlight rolloff, shallow cinematic depth of field, natural filmic color science",
  },
  {
    value: "放送用ビデオカメラ",
    hint: "報道・全部はっきり",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "broadcast-video-camera", "放送用ビデオカメラ"),
    prompt:
      "shot on a shoulder-mount broadcast video camera, deep depth of field keeping subject and location both sharp, neutral news-broadcast rendering, video-style motion look",
  },
  {
    value: "大判ビューカメラ",
    hint: "建築向き・面が薄い",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "large-format-view-camera", "大判ビューカメラ"),
    prompt:
      "shot on a large-format view camera, extremely shallow razor-thin plane of focus with tilt-shift control, hyper-detailed edge-to-edge resolution, perfectly straight corrected verticals",
  },
  {
    value: "中判フィルム",
    hint: "高精細・上品なボケ",
    visual: "camera-film",
    thumbnail: thumb("camera_equipment", "medium-format-film", "中判フィルム"),
    prompt:
      "shot on medium format film, very shallow depth of field with smooth gradual falloff, exceptionally fine detail and tonal gradation, refined natural color",
  },
  {
    value: "フィルムカメラ",
    hint: "粒状・温かみ",
    visual: "camera-film",
    thumbnail: thumb("camera_equipment", "film-camera", "フィルムカメラ"),
    prompt:
      "shot on 35mm film, organic grain, warm color reproduction, gentle highlight rolloff, moderately shallow depth of field",
  },
  {
    value: "レンジファインダー",
    hint: "素直な画・スナップ向き",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "vintage-rangefinder", "レンジファインダー"),
    prompt:
      "shot on a vintage rangefinder camera, moderate depth of field, quiet unobtrusive street framing, honest low-contrast optics with subtle vintage character",
  },
  {
    value: "二眼レフ",
    hint: "正方形・見上げる目線",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "twin-lens-reflex", "二眼レフ"),
    prompt:
      "shot on a twin-lens reflex camera, square 6x6 framing, waist-level low camera height, medium depth of field, soft classic film tonality",
  },
  {
    value: "インスタントカメラ",
    hint: "色が転ぶ・白フチ",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "instant-camera", "インスタントカメラ"),
    prompt:
      "shot on instant film, soft low-resolution optics, fairly deep depth of field, shifted pastel color cast, slightly blown highlights and milky shadows",
  },
  {
    value: "VHS",
    hint: "ローファイ・90年代",
    visual: "camera-retro",
    thumbnail: thumb("camera_equipment", "vhs", "VHS"),
    prompt:
      "recorded on VHS tape, lo-fi 90s video aesthetic, scan lines, chroma smear, soft tape texture, deep unrefined depth of field",
  },
  {
    value: "アクションカメラ",
    hint: "超広角・全体にピント",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "action-camera", "アクションカメラ"),
    prompt:
      "shot on a wearable action camera, ultra-wide barrel-distorted field of view, very deep depth of field with everything in focus, close-to-subject high-energy perspective",
  },
  {
    value: "ドローンカメラ",
    hint: "上から俯瞰・全部シャープ",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "drone-camera", "ドローンカメラ"),
    prompt:
      "shot from an aerial drone camera, high elevated vantage point looking down, wide field of view, deep depth of field with the whole landscape sharp, smooth gimbal-stabilized framing",
  },
  {
    value: "ウェブカメラ",
    hint: "配信っぽい・粗い",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "webcam", "ウェブカメラ"),
    prompt:
      "shot on a webcam, fixed frontal eye-level framing, deep flat depth of field, mild digital noise and compression softness, plain video-call rendering",
  },
  {
    value: "ハイスピードカメラ",
    hint: "止まった瞬間・硬い光",
    visual: "camera-digital",
    thumbnail: thumb("camera_equipment", "high-speed-camera", "ハイスピードカメラ"),
    prompt:
      "shot on a high-speed camera, extreme slow-motion frozen instant, zero motion blur, crisp frozen droplets and debris, medium depth of field under bright hard light",
  },
];

/**
 * ショット幅（旧 焦点距離 + レンズ を統合）。
 *
 * 元は焦点距離（mm 数値） と レンズ種類（魚眼/望遠 等）が別軸で、
 * 「8mm = 魚眼」「200mm = 望遠」が両軸に重複していた。
 * 中級プロでも数値より「効果名」で選ぶ方が早いため 1 軸に統合。
 *
 * value は日本語ラベル（中級プロが読みやすい）、prompt は英語完成形。
 */
/**
 * 構図の選択肢を役割グループで絞る。UI は3つの独立した選択として出す。
 *
 * 3つは併用できる (「胸上まで寄って・下から見上げて・左に寄せる」) ので、
 * 1つの一覧から1つだけ選ばせる形では表現できない (2026-07-27 STΛCK 指摘)。
 * 各グループの先頭には「指定なし」を必ず置く (選ばない自由を残す)。
 */
export function compositionOptionsFor(group: CompositionGroup): SceneOption[] {
  return [NO_SELECT_OPTION, ...compositionOptions.filter((o) => o.group === group)];
}

export const shotOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  {
    value: "超広角14mm",
    hint: "空間が大きく歪む",
    visual: "focal",
    thumbnail: thumb("shot", "14mm", "超広角14mm"),
    prompt:
      "14mm ultra-wide-angle lens, extreme field of view, strongly stretched perspective",
  },
  {
    value: "広角24mm",
    hint: "周囲がぐっと入る",
    visual: "focal",
    thumbnail: thumb("shot", "24mm", "広角24mm"),
    prompt:
      "24mm wide-angle lens, broad field of view, expanded perspective",
  },
  {
    value: "広角",
    hint: "自然な広さで空間も入る",
    visual: "focal",
    thumbnail: thumb("shot", "35mm", "広角"),
    prompt:
      "35mm wide-angle lens, generous natural field of view, mild perspective",
  },
  {
    value: "標準",
    hint: "肉眼どおりの見え方",
    visual: "focal",
    thumbnail: thumb("shot", "50mm", "標準"),
    prompt:
      "50mm standard lens, natural human-eye perspective, neutral depth rendering",
  },
  {
    value: "ポートレート",
    hint: "背景が寄って主役が浮く",
    visual: "focal",
    thumbnail: thumb("shot", "85mm", "ポートレート"),
    prompt:
      "85mm short-telephoto lens, mild compression, shallow depth of field, clean subject separation",
  },
  {
    value: "中望遠135mm",
    hint: "背景が壁のように迫る",
    visual: "focal",
    thumbnail: thumb("shot", "135mm", "中望遠135mm"),
    prompt:
      "135mm telephoto lens, marked compression, flattened background plane",
  },
  {
    value: "望遠",
    hint: "奥行きが潰れて平面的",
    visual: "focal",
    thumbnail: thumb("shot", "200mm", "望遠"),
    prompt:
      "200mm long-telephoto lens, strong compression, collapsed depth, flat layered planes",
  },
  {
    value: "超望遠300mm",
    hint: "奥行きが完全に消える",
    visual: "focal",
    thumbnail: thumb("shot", "300mm", "超望遠300mm"),
    prompt:
      "300mm super-telephoto lens, maximum compression, depth cues nearly removed",
  },
  {
    value: "マクロ接写",
    hint: "手だけを極端に寄る",
    visual: "focal",
    thumbnail: thumb("shot", "macro", "マクロ接写"),
    prompt:
      "macro lens at minimum focus distance, life-size detail, extremely shallow plane of focus",
  },
  {
    value: "ティルトシフト",
    hint: "1本の帯だけピント",
    visual: "focal",
    thumbnail: thumb("shot", "tilt-shift", "ティルトシフト"),
    prompt:
      "tilt-shift lens, tilted plane of focus, narrow sharp band, miniature-model impression",
  },
  {
    value: "超広角・魚眼",
    hint: "画面全体が丸く反る",
    visual: "focal",
    thumbnail: thumb("shot", "fisheye", "超広角・魚眼"),
    prompt:
      "8mm fisheye lens, pronounced barrel distortion, near-180-degree field of view",
  },
  {
    value: "アナモルフィック",
    hint: "横長・楕円ボケ",
    visual: "focal",
    thumbnail: thumb("shot", "anamorphic", "アナモルフィック"),
    prompt:
      "anamorphic lens, wider horizontal field of view, oval bokeh, subtle horizontal stretch",
  },
];

// filmOptions は削除済み。フィルム種類（Cinestill/Kodak/Fuji 等）は
// スタイル軸に内包される（例: ストリート粒子 / モノクロストリート / ネオノワール）。
// ここに再追加せず、必要ならスタイル新設で対応する。

/**
 * 統合スタイル軸。1 個選ぶだけで「ジャンル + 色味 + 質感」が完成形で
 * プロンプトに乗る。旧 photographerStyle / cinematicLook / filter を統合。
 *
 * Why: ユーザー視点で「結局どれを選べば絵の雰囲気が決まるのか」が分かりにくい
 * ため、3 軸を 1 軸に畳む。微調整したい上級者は promptOverride で
 * 英語プロンプトを直接編集できる。
 *
 * thumbnail は既存資産（cinematic_look / photographer の生成済み 11 枚）を
 * リネーム移動なしで参照する。新スタイルの新規サムネは段階的に差し替える。
 */
export const styleOptions: SceneOption[] = [
  NO_SELECT_OPTION,
  // 2026-07-27 統合: 旧「クリーンコマーシャル」と旧「photorealistic」を1本にまとめた。
  //
  // なぜ: 両者は「加工感のない実写」という同じことを別の言葉で言っており、同じ被写体を
  // 同じ構図で生成すると出力が実質同一になる（サムネ検品で「背景の白さがわずかに違う
  // だけで判別不能」と実測）。言葉が違っても選んだ結果が変わらない選択肢は、選ぶ側の
  // 負担を増やすだけで機能しない。
  //
  // 旧 value を保存していたプリセットは buildPrompt.stylePiece のフォールバック
  // （styleOptions に無い value はそのまま prompt に渡る）で従来どおり動く。
  {
    value: "実写・広告写真",
    hint: "加工感のない実写・広告の清潔さ",
    visual: "style",
    thumbnail: thumb("style", "photorealistic", "実写・広告写真"),
    prompt:
      "photorealistic commercial photography, true-to-life materials and micro-surface texture, crisp edge-to-edge sharpness, polished neutral finish, natural optical depth of field, unprocessed neutral color",
  },
  {
    value: "ドキュメンタリーリアリズム",
    hint: "報道写真の素っ気なさ",
    visual: "style",
    thumbnail: thumb("style", "documentary-realism", "ドキュメンタリーリアリズム"),
    prompt:
      "documentary photojournalism rendering, unretouched reportage look, honest flat neutral color, fine natural 35mm grain",
  },
  {
    value: "エディトリアルポートレート",
    hint: "雑誌の質感・きれいに整う",
    visual: "style",
    thumbnail: thumb("style", "editorial-portrait", "エディトリアルポートレート"),
    prompt:
      "editorial fashion magazine rendering, refined medium-format clarity, smooth tonal gradation, immaculate retouched surfaces",
  },
  {
    value: "大判建築",
    hint: "隅々まで異様に解像する",
    visual: "style",
    thumbnail: thumb("style", "large-format-architectural", "大判建築"),
    prompt:
      "large-format technical photography rendering, hyper-detailed resolution across the whole frame, rectilinear geometry, deep uniform focus",
  },
  {
    value: "シネマティックフィルム",
    hint: "映画のワンカットに見える",
    visual: "style",
    thumbnail: thumb("style", "cinematic-film", "シネマティックフィルム"),
    prompt:
      "cinematic 35mm motion-picture film rendering, anamorphic edge softness, filmic highlight rolloff, subtle organic grain",
  },
  {
    value: "ミュートドラマ",
    hint: "彩度を殺して重くする",
    visual: "style",
    thumbnail: thumb("style", "muted-drama", "ミュートドラマ"),
    prompt:
      "muted painterly film rendering, heavily desaturated palette, low contrast, soft matte surfaces, restrained classical tonality",
  },
  {
    value: "パステル昼光",
    hint: "色が淡く軽く抜ける",
    visual: "style",
    thumbnail: thumb("style", "pastel-daylight", "パステル昼光"),
    prompt:
      "pastel high-key film rendering, lifted blacks, airy pale tonality, gentle low-contrast gradation, delicate soft grain",
  },
  {
    value: "ハイコントラスト劇的",
    hint: "黒が潰れて白が飛ぶ",
    visual: "style",
    thumbnail: thumb("style", "high-contrast", "ハイコントラスト劇的"),
    prompt:
      "high-contrast graphic rendering, crushed deep blacks, clean blown whites, steep tonal curve, hard-edged value separation",
  },
  {
    value: "ネオノワール",
    hint: "黒が深く沈むノワール",
    visual: "style",
    thumbnail: thumb("style", "neo-noir", "ネオノワール"),
    prompt:
      "neo-noir film rendering, dense inky shadow density, cool desaturated grade, glossy hard surface sheen, heavy filmic contrast",
  },
  // 2026-07-27 統合: 旧「モノクロストリート」を「ストリート粒子」に寄せて1本にした。
  //
  // なぜ: 検品で旧モノクロストリートは「ストリート粒子から粒を抜いた残り」に見えると
  // 判定された。白黒でどう見せるかの性格が「粒子の粗さ」しか無く、その粗さを持つ側と
  // 持たない側を別項目にすると、後者に選ぶ理由が説明できない。
  // 白黒の階調表現は「ハイコントラスト劇的」（硬調）と本項目（粒子）で足りる。
  //
  // 旧 value「モノクロストリート」を保存していたプリセットは
  // buildPrompt.stylePiece のフォールバックで従来どおり動く。
  {
    value: "モノクロ・粒子",
    hint: "白黒・粒子でざらつく",
    visual: "style",
    thumbnail: thumb("style", "street-grain", "モノクロ・粒子"),
    prompt:
      "gritty high-ISO black-and-white rendering, fully monochrome, coarse heavy grain, harsh blown contrast, rough push-processed texture, darkroom print finish",
  },
  {
    value: "アメリカーナ叙情",
    hint: "退色した昔の写真感",
    visual: "style",
    thumbnail: thumb("style", "americana-lyric", "アメリカーナ叙情"),
    prompt:
      "faded vintage color negative rendering, aged dye shift, soft low-saturation palette, gentle analog softness, mild visible grain",
  },
  {
    value: "3Dレンダー",
    hint: "CGらしいツルツルの立体",
    visual: "style",
    thumbnail: thumb("style", "3d-render", "3Dレンダー"),
    prompt:
      "modern 3D CGI render, physically based matte shader, smooth synthetic surfaces, clean raytraced ambient occlusion",
  },
  {
    value: "クレイアニメ",
    hint: "粘土細工の手作り感",
    visual: "style",
    thumbnail: thumb("style", "claymation", "クレイアニメ"),
    prompt:
      "stop-motion claymation rendering, sculpted plasticine surfaces with fingerprint dents, soft handmade irregularity, tactile miniature feel",
  },
  {
    value: "油彩画",
    hint: "絵の具の厚みが見える",
    visual: "style",
    thumbnail: thumb("style", "oil-painting", "油彩画"),
    prompt:
      "traditional oil painting on canvas, thick impasto brush strokes, visible bristle marks, woven canvas texture, painterly edges",
  },
  {
    value: "水彩画",
    hint: "にじみと余白で軽い",
    visual: "style",
    thumbnail: thumb("style", "watercolor", "水彩画"),
    prompt:
      "watercolor painting on cold-press paper, translucent washes, soft bleeding pigment edges, wet-on-wet blooms, white paper highlights",
  },
  {
    value: "鉛筆スケッチ",
    hint: "手描きの下描きに見える",
    visual: "style",
    thumbnail: thumb("style", "pencil-sketch", "鉛筆スケッチ"),
    prompt:
      "graphite pencil sketch on sketchbook paper, hand-drawn contour lines, cross-hatched shading, visible construction lines and eraser smudges",
  },
  {
    value: "アニメ",
    hint: "アニメのセル画になる",
    visual: "style",
    thumbnail: thumb("style", "anime", "アニメ"),
    prompt:
      "Japanese anime cel rendering, clean uniform ink outlines, flat two-tone cel shading with hard shadow edges, limited palette",
  },
  {
    value: "漫画線画",
    hint: "白黒漫画の線とトーン",
    visual: "style",
    thumbnail: thumb("style", "manga-line-art", "漫画線画"),
    prompt:
      "black-and-white manga line art, crisp variable-weight ink linework, screentone halftone shading, pure black and white only",
  },
  {
    value: "リソグラフ印刷",
    hint: "版ズレしたZINE印刷",
    visual: "style",
    thumbnail: thumb("style", "risograph", "リソグラフ印刷"),
    prompt:
      "risograph print rendering, coarse halftone dot screens, slight ink misregistration, uneven ink coverage, matte recycled paper texture",
  },
  {
    value: "スクリーン印刷",
    hint: "ポスター版画の平べったさ",
    visual: "style",
    thumbnail: thumb("style", "screen-print", "スクリーン印刷"),
    prompt:
      "silkscreen poster print rendering, posterized flat tonal blocks, hard-edged stencil separations, squeegee ink texture, heavy paper stock",
  },
  {
    value: "ベクターフラット",
    hint: "アイコン的にのっぺりする",
    visual: "style",
    thumbnail: thumb("style", "vector-flat", "ベクターフラット"),
    prompt:
      "flat vector illustration, clean geometric shapes, solid uniform fills, no gradients, crisp mathematical edges, icon-like reduction",
  },
  {
    value: "ピクセルアート",
    hint: "ドット絵に粗く落ちる",
    visual: "style",
    thumbnail: thumb("style", "pixel-art", "ピクセルアート"),
    prompt:
      "low-resolution pixel art rendering, visible square pixel grid, hard aliased edges, limited index palette, dithered shading, no anti-aliasing",
  },
  {
    value: "設計図ブループリント",
    hint: "図面・線だけの設計図",
    visual: "style",
    thumbnail: thumb("style", "blueprint-technical", "設計図ブループリント"),
    prompt:
      "technical blueprint drafting rendering, precise thin uniform outlines, orthographic engineering-drawing clarity, no fills, no shading",
  },
  {
    value: "ワイヤーフレーム",
    hint: "骨組みだけの線メッシュ",
    visual: "style",
    thumbnail: thumb("style", "wireframe", "ワイヤーフレーム"),
    prompt:
      "3D wireframe rendering, open polygon mesh of thin edge lines, visible topology, no surface shading, CAD viewport look",
  },
];

export const referenceSlotIds: ReferenceSlotId[] = [
  "@img1",
  "@img2",
  "@img3",
  "@img4",
  "@img5",
];
