import { describe, expect, it } from "vitest";
import {
  buildRemoteMcpParams,
  classifyRemoteMcpTool,
  groupRemoteMcpTools,
  remoteMcpSchemaHasModelField,
  type RemoteMcpToolLike,
} from "../src/lib/remoteMcpTools";

type MeasuredClassificationFixture = {
  provider: string;
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  expected: "image" | "video" | "other";
};

// 2026-08-24 の MCP 実測 JSON を固定。_work の更新にテスト結果を連動させない。
const MEASURED_CLASSIFICATION_FIXTURES: MeasuredClassificationFixture[] =
  [
    {
      "provider": "kling",
      "name": "text_to_image",
      "description": "Generate images from a text prompt with Kling AI. Call who_am_i first to discover the available models and each model's argument specification. Returns a generation_id immediately; poll query_tasks for the image URLs.- If user intent or any parameter is uncertain, ask first. Every job is charged; do not submit trial jobs.- If user uses alias words, map to canonical names and pass canonical only. Do not invent names or value.- On timeout/long hang/failure/unexpected result, keep user informed. Ask user whether to retry or change parameters. Do not auto-resubmit or silently change intent/parameters. Soft constraint: text_to_image does NOT support subjects (Elements) at all — neither image nor video subjects. Never pass an 'elements' argument or a <<<id>>> subject binding here. If the user wants to generate with a subject, use image_to_image (image subject) or image_to_video (video subject) instead.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "description": "Model to use; must be one of the models listed for this tool in who_am_i's availableModels. Required: there is no default model. Call who_am_i first and choose the model whose description best fits the user's request."
          },
          "arguments": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "value"
              ]
            },
            "description": "Generation arguments as name/value pairs, e.g. [{\"name\": \"prompt\", \"value\": \"a cat\"}]. All values are strings. Required names, defaults and allowed values are declared per model in who_am_i."
          },
          "inputs": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "inputType": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "inputType",
                "name",
                "url"
              ]
            },
            "description": "Resource inputs as declared per model in who_am_i; each item is {name, inputType: 'URL', url}. Omit when the chosen model declares no inputs."
          },
          "rationale": {
            "type": "string",
            "description": "Detailed purpose explaining the user's core objective for invoking this tool, including contextual reasoning behind parameter selections. Example: \"User uploaded a personal artwork image and requested a short animated clip for personal sharing; resolution set to 4K per explicit user demand for maximum visual clarity\"."
          },
          "taskTraceId": {
            "type": "string",
            "description": "RFC 4122 UUID V7 identifier to group consecutive, logically connected operations under one user task intent. The same ID is reused for chained steps completing a single goal, such as generating an image then converting it to video for the same subject. A fresh unique UUID must be assigned once the user switches to an unrelated new task, isolating execution traces across distinct user requests."
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "expected": "image"
    },
    {
      "provider": "kling",
      "name": "image_to_image",
      "description": "Generate new images or edit images from reference image(s) and a text prompt with Kling AI. Call who_am_i first to discover the available models, each model's argument specification, and its required inputs. Input URLs must either be links returned by the file_upload tool for local uploads, or publicly accessible external file URLs. Supported image specs: PNG/JPG only, below 4K resolution, ≤30MB, aspect ratio no wider than 1:2. URLs generated by prior Kling tasks can be used directly without downloading or validation. Returns a generation_id immediately; poll query_tasks for the result. - If user intent or any parameter is uncertain, ask first. Every job is charged; do not submit trial jobs.- If user uses alias words, map to canonical names and pass canonical only. Do not invent names or value.- On timeout/long hang/failure/unexpected result, keep user informed. Ask user whether to retry or change parameters. Do not auto-resubmit or silently change intent/parameters. Image-subject binding: image_to_image CAN bind image subjects (cover + secondary, no resource.video) on every model that lists 'elements', INCLUDING kling-image-o1. Never refuse an image-subject request just because the model is kling-image-o1. Video-subject binding: image_to_image CANNOT bind video subjects. If element_get shows resource.video, tell the user first and use image_to_video with kling-video-v3_0_omni or kling-video-v3_0 instead.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "description": "Model to use; must be one of the models listed for this tool in who_am_i's availableModels. Required: there is no default model. Call who_am_i first and choose the model whose description best fits the user's request."
          },
          "arguments": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "value"
              ]
            },
            "description": "Generation arguments as name/value pairs, e.g. [{\"name\": \"prompt\", \"value\": \"a cat\"}]. All values are strings. Required names, defaults and allowed values are declared per model in who_am_i."
          },
          "inputs": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "inputType": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "inputType",
                "name",
                "url"
              ]
            },
            "description": "Resource inputs as declared per model in who_am_i; each item is {name, inputType: 'URL', url}. Omit when the chosen model declares no inputs."
          },
          "rationale": {
            "type": "string",
            "description": "Detailed purpose explaining the user's core objective for invoking this tool, including contextual reasoning behind parameter selections. Example: \"User uploaded a personal artwork image and requested a short animated clip for personal sharing; resolution set to 4K per explicit user demand for maximum visual clarity\"."
          },
          "taskTraceId": {
            "type": "string",
            "description": "RFC 4122 UUID V7 identifier to group consecutive, logically connected operations under one user task intent. The same ID is reused for chained steps completing a single goal, such as generating an image then converting it to video for the same subject. A fresh unique UUID must be assigned once the user switches to an unrelated new task, isolating execution traces across distinct user requests."
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "expected": "video"
    },
    {
      "provider": "magnific",
      "name": "video_speak",
      "description": "Make a character speak. Image+audio → talking head (Veed Fabric 1.0). Video+audio → lip sync (Lipsync 2.0). Omit `mode` for auto. Pass asset URLs or a creation `identifier` (from `audio_tts`, `images_generate`, `video_generate`). Then call `creations_show`.",
      "inputSchema": {
        "properties": {
          "audioUrl": {
            "description": "Asset URL or a creation `identifier` (from `audio_tts`).",
            "type": "string"
          },
          "videoUrl": {
            "description": "Asset URL or a creation `identifier`. Required without `imageUrl`; mutually exclusive with it.",
            "type": "string"
          },
          "imageUrl": {
            "description": "Asset URL or a creation `identifier`. Required without `videoUrl`; mutually exclusive with it.",
            "type": "string"
          },
          "mode": {
            "description": "Omit for auto: image → veed-fabric-1.0, video → lipsync-2.0.",
            "enum": [
              "latentsync",
              "lipsync-2.0",
              "omnihuman",
              "veed-fabric-1.0",
              "veed-fabric-1.0-fast",
              "veed-sync-2-v2v",
              "react-1"
            ],
            "type": "string"
          },
          "resolution": {
            "description": "Only for veed modes; defaults to 720p.",
            "enum": [
              "480p",
              "720p"
            ],
            "type": "string"
          },
          "prompt": {
            "description": "Script/prompt; model-dependent support.",
            "type": "string"
          },
          "voiceId": {
            "description": "Voice ID from `audio_voices_list`; links the voice to the creation.",
            "type": "integer"
          },
          "folderReference": {
            "description": "From `folders_list`. Omit → the user's Personal project. Does NOT persist: once the user names a target, pass it on EVERY later generation/edit call.",
            "type": "string"
          }
        },
        "type": "object",
        "required": [
          "audioUrl"
        ]
      },
      "expected": "other"
    },
    {
      "provider": "pika",
      "name": "generate_reference_video",
      "description": "Generate a video from multi-modal reference inputs (images, videos, audio) used as character / style / motion anchors — NOT as start frames. **Default: kling** (omni-video, sound-capable, up to 7 image / 3 video / 8 audio refs). Specialist: seedance — cinematic look, supports `fast` / `seed` / `resolution` / `auto_duration`, accepts up to 9 image / 3 video / 3 audio refs (combined ≤ 12). Specialist: minimax — S2V-01 single-subject consistent-character mode (exactly 1 reference_image, no videos or audio). Subject must be a HUMAN face (animals/objects fail subject extraction). Specialist: minimax-h3 — Hailuo 03 multimodal refs (up to 9 image / 3 video / 3 audio), 2K output, 5-15s, always-on native stereo audio.\n\nReference assets in prompt via <<<image_1>>>/<<<video_1>>> (kling), @Image1/@Video1/@Audio1 (seedance), or plain `Image 1`/`Video 1`/`Audio 1` by list position (minimax-h3 — do NOT use @ tokens there).\n\nSound defaults to on; pass sound=false to suppress. For text- or single-image-driven video use `generate_video` instead.\n\nReturns the result inline when complete (typically 30s–5min). Progress updates are sent as notifications during execution. If the server budget expires before completion, falls back to `{ task_id, status }` — then call `task_status(task_id)` in a tight loop (no Bash, no sleep) until status is `completed`, `failed`, or `cancelled`.",
      "inputSchema": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "provider": {
            "description": "Which video model. **Default: kling** — fastest + cheapest, omni-video supports sound + up to 7/3/8 refs. seedance for cinematic look, fast tier, seed control, auto duration, routed through BytePlus ModelArk. minimax for S2V-01 single-subject (exactly 1 reference_image). Subject must be a HUMAN face (animals/objects fail subject extraction). minimax-h3 for MiniMax Hailuo 03 multimodal refs — up to 9 image / 3 video / 3 audio, 2K output, 5-15s, `seed` supported, always-on native stereo audio; cite refs as `Image 1` / `Video 1` / `Audio 1` by list position. omni for Gemini Omni Flash r2v — image refs only, fixed ~10s clip with native audio; result includes an interaction_id usable with generate_video_edit for conversational follow-up edits.",
            "type": "string",
            "enum": [
              "kling",
              "seedance",
              "minimax",
              "minimax-h3",
              "omni"
            ]
          },
          "prompt": {
            "type": "string",
            "minLength": 1,
            "description": "Description or motion direction. Use @Image1 / @Video1 / @Audio1 tokens (seedance) or <<<image_1>>> / <<<video_1>>> tokens (kling) to anchor specific references."
          },
          "reference_images": {
            "description": "Reference image URLs. **Multi-ref is supported — pass an array of character / style anchors (NOT start frames).** Accepts an existing, reachable HTTPS URL directly. Local paths, `file://`, `MEDIA:`, and attached media are handled by the shared media resolver when the call includes file bytes; remote-only callers that only have a path string must use a client-side resolver such as `pika-upload-file` first and pass the resulting HTTPS URL. **Attach a reference whenever the request is about a specific person or recurring character — the user, 'me', 'my character', or the bot/yourself. A text prompt alone will NOT preserve identity; pass the actual photo here. If the only copy is a local chat-uploaded file (e.g. a path like /data/.pikabot/media/inbound/*.png), pass it through a client-side media resolver so the tool receives file bytes or an HTTPS URL.** Per-provider caps: seedance up to 9 (jpeg/png/webp, ≤30MB each); kling up to 7. Requires at least one entry here or in reference_videos.",
            "maxItems": 9,
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "minLength": 1
                },
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {},
                  "description": "Media reference object. For small inline uploads up to 3145728 decoded bytes, include filename, mime_type, and bytes_base64. Use upload_asset for larger files."
                }
              ]
            }
          },
          "reference_videos": {
            "description": "Reference video URLs (motion / style). Up to 3 videos. Requires at least one entry here or in reference_images. Accepts an existing, reachable HTTPS URL directly. Local paths, `file://`, `MEDIA:`, and attached media are handled by the shared media resolver when the call includes file bytes; remote-only callers that only have a path string must use a client-side resolver such as `pika-upload-file` first and pass the resulting HTTPS URL.",
            "maxItems": 3,
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "minLength": 1
                },
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {},
                  "description": "Media reference object. For small inline uploads up to 3145728 decoded bytes, include filename, mime_type, and bytes_base64. Use upload_asset for larger files."
                }
              ]
            }
          },
          "reference_audio": {
            "description": "Reference audio URLs. **Multi-ref is supported on both providers — pass an array.** Per-provider caps: seedance accepts up to 3 (combined ≤ 15s, mp3 / wav only); kling accepts up to 8 (mp3 / wav / m4a). Reference via @Audio1/@Audio2/@Audio3 tokens (seedance) or paired with the prompt (kling). Accepts an existing, reachable HTTPS URL directly. Local paths, `file://`, `MEDIA:`, and attached media are handled by the shared media resolver when the call includes file bytes; remote-only callers that only have a path string must use a client-side resolver such as `pika-upload-file` first and pass the resulting HTTPS URL.",
            "maxItems": 8,
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "minLength": 1
                },
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {},
                  "description": "Media reference object. For small inline uploads up to 3145728 decoded bytes, include filename, mime_type, and bytes_base64. Use upload_asset for larger files."
                }
              ]
            }
          },
          "duration": {
            "description": "Length in seconds (default 5). Per-provider valid values: kling 3-15 · seedance 4-15 · minimax-h3 5-15. For seedance auto-length, pass `auto_duration: true` instead — `duration` is then ignored. When `shots` is present, omit `duration`; the output length is derived from `sum(shots[].duration)`.",
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "auto_duration": {
            "description": "Let Seedance pick the best clip length automatically. seedance only — rejected on kling/minimax. Maps to ModelArk duration=-1. When true, the `duration` field is ignored. Default false.",
            "type": "boolean"
          },
          "aspect_ratio": {
            "description": "Output aspect ratio (default 16:9). `21:9`, `4:3`, `3:4`, `auto` are seedance-only — passing them on kling is rejected.",
            "type": "string",
            "enum": [
              "16:9",
              "9:16",
              "1:1",
              "21:9",
              "4:3",
              "3:4",
              "auto"
            ]
          },
          "sound": {
            "description": "Enable ambient audio. If omitted, defaults to true on both providers. Pass sound=false explicitly to suppress audio.",
            "type": "boolean"
          },
          "seed": {
            "description": "Reproducibility seed. seedance only (echoed in result). Rejected on kling.",
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "seedance_model": {
            "description": "Seedance model tier. `standard` (default — full quality, up to 4k) | `fast` (cheaper, ~20% off, caps at 720p) | `mini` (cheapest + fastest, caps at 720p). seedance only. Canonical tier knob; the legacy `fast` boolean is a back-compat alias for `seedance_model=fast`; `fast=true` with a non-fast `seedance_model` is rejected, while `fast=false` is treated as omitted.",
            "type": "string",
            "enum": [
              "standard",
              "fast",
              "mini"
            ]
          },
          "fast": {
            "description": "DEPRECATED alias for `seedance_model=fast`. Use the fast (cheaper, ~20% off) seedance tier. seedance only. Caps resolution at 720p — combining with `resolution=1080p` or `4k` is rejected. Prefer `seedance_model`.",
            "type": "boolean"
          },
          "resolution": {
            "description": "Output resolution. seedance (default 720p — 1080p and 4k require the standard tier, since fast and mini cap at 720p; 4k outputs HEVC/10-bit) and minimax-h3 (2k only — H3's sole supported output, so the field is optional there).",
            "type": "string",
            "enum": [
              "480p",
              "720p",
              "1080p",
              "2k",
              "4k"
            ]
          },
          "shots": {
            "description": "Multi-shot narrative segments. kling only. 1-6 shots, each with its own prompt + duration. Omit top-level `duration` when using shots; output length is derived from `sum(shots[].duration)`, which must be 3-15 seconds total.",
            "minItems": 1,
            "maxItems": 6,
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "prompt": {
                  "type": "string",
                  "minLength": 1
                },
                "duration": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 15
                }
              },
              "required": [
                "prompt",
                "duration"
              ]
            }
          },
          "prompt_adherence": {
            "description": "How strictly to follow the prompt. loose ≈ 0.3 (more creative interpretation), balanced ≈ 0.5 (default), strict ≈ 0.85 (literal). Kling only.",
            "type": "string",
            "enum": [
              "loose",
              "balanced",
              "strict"
            ]
          },
          "negative_prompt": {
            "description": "What the model should AVOID generating. Kling only. Common patterns: 'blur, distortion, low quality'; 'watermarks, text overlay, logos'; 'deformed anatomy, extra fingers'.",
            "type": "string",
            "maxLength": 2500
          },
          "watermark": {
            "description": "Burn kling's watermark into the output. Default `false` — clean output by default. Pass `true` to opt back into kling's account-tier-dependent watermark. Kling only.",
            "type": "boolean"
          },
          "image_types": {
            "description": "Per-image role for reference_images (parallel array, same length). \"first_frame\" → starting frame; \"end_frame\" → ending frame; \"reference\" or null → plain style/character reference. Kling only. kling-video-o1 limits first/end frame usage when >2 images total.",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "enum": [
                    "first_frame",
                    "end_frame",
                    "reference"
                  ]
                },
                {
                  "type": "null"
                }
              ]
            }
          },
          "video_refer_types": {
            "description": "Per-video role for reference_videos (parallel array, same length). \"feature\" = character/style reference; \"base\" = video to restyle/edit. Default: all feature. Kling only.",
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "feature",
                "base"
              ]
            }
          },
          "video_keep_sounds": {
            "description": "Per-video flag: preserve original audio track (parallel array to reference_videos). Default: false for all. Kling only.",
            "type": "array",
            "items": {
              "type": "boolean"
            }
          },
          "element_ids": {
            "description": "Kling subject library element IDs to bind (up to 3). Create elements first with create_kling_element. Kling only.",
            "minItems": 1,
            "maxItems": 3,
            "type": "array",
            "items": {
              "type": "integer",
              "minimum": -9007199254740991,
              "maximum": 9007199254740991
            }
          },
          "kling_model": {
            "description": "Omni model variant (default \"kling-v3-omni\"). Kling only.",
            "type": "string",
            "enum": [
              "kling-v3-omni",
              "kling-video-o1"
            ]
          },
          "quality_mode": {
            "description": "Output quality tier. \"std\" = 720p; \"pro\" = 1080p (default); \"4k\" = 4K. Kling only.",
            "type": "string",
            "enum": [
              "std",
              "pro",
              "4k"
            ]
          },
          "intelligence_shot": {
            "description": "Let Kling auto-determine shot breakdown from the prompt (shot_type=intelligence). Mutually exclusive with shots[]. Kling only.",
            "type": "boolean"
          },
          "voice_ids": {
            "description": "Cloned voice IDs from `clone_voice`. Pass voice_ids for previously-cloned voices (small payload — Kling stores the binary server-side); pass `reference_audio` for ad-hoc inline audio (forces base64 binary in the request body — large). **Use voice_ids whenever possible** to avoid request-size limits. Combined `len(voice_ids) + len(reference_audio)` is capped at 8 (Kling upstream cap). Kling only — rejected on seedance.",
            "minItems": 1,
            "maxItems": 8,
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "callback_url": {
            "description": "Webhook URL Kling will POST to when generation completes. Useful for fire-and-forget patterns where the caller doesn't want to poll. Must be https://. Kling only.",
            "type": "string",
            "format": "uri",
            "pattern": "^https:\\/\\/.*"
          },
          "external_task_id": {
            "description": "Caller-supplied tracing identifier passed through to Kling (echoed back in upstream task records). Useful for correlating Pika job IDs with downstream systems. ≤64 chars. Kling only.",
            "type": "string",
            "minLength": 1,
            "maxLength": 64
          },
          "background": {
            "description": "Run in background: if true, return {task_id, status:\"running\"} immediately so the caller can poll task_status({task_id}) later. Useful when the user wants to keep chatting / doing other work while this renders. If false or omitted, blocks up to 260s and returns the inline result. Default: false.",
            "type": "boolean"
          },
          "confirm_token": {
            "description": "Confirmation token returned by a prior cost_confirmation_required response. Re-call the same tool with the exact same arguments plus this token only after the user approves the surfaced cost estimate.",
            "type": "string"
          }
        },
        "required": [
          "prompt"
        ]
      },
      "expected": "other"
    },
    {
      "provider": "pika",
      "name": "generate_video_edit",
      "description": "Edit an existing video with a free-form prompt via Gemini Omni Flash: restyle (\"Make this video anime\"), add/remove objects, relight, change wardrobe or weather — the model preserves everything the prompt does not mention. Provide EXACTLY ONE source: `video_url` or `previous_interaction_id` (returned by a prior generate_video_edit or generate_reference_video provider=omni call) to keep iterating on that result without re-uploading. Sources longer than ~10s are silently TRUNCATED — only the first ~10s gets edited. Output keeps the source length (up to ~10s) with native audio and INHERITS the source aspect (16:9 and 9:16 both preserved; other aspects like 1:1 snap to 16:9 with cropping). The result includes a new `interaction_id` for the next edit turn. Keep prompts simple and append \"Keep everything else the same\" when changing one aspect. Optionally include up to 6 `reference_images` for visual style, product, or character guidance; bind each in the prompt with `<IMAGE_REF_0>`, `<IMAGE_REF_1>`, etc. Images are references, not start frames. Editing uploaded videos is unavailable in EEA/CH/UK (chained edits of omni-generated videos still work there).\n\nReturns the result inline when complete (typically 30s–5min). Progress updates are sent as notifications during execution. If the server budget expires before completion, falls back to `{ task_id, status }` — then call `task_status(task_id)` in a tight loop (no Bash, no sleep) until status is `completed`, `failed`, or `cancelled`.",
      "inputSchema": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "prompt": {
            "type": "string",
            "minLength": 1,
            "description": "The edit instruction. Simple prompts work best (\"Make this video anime\", \"Put a fashionable hat on this person\"); append \"Keep everything else the same\" when changing one aspect."
          },
          "video_url": {
            "description": "Source video to edit (any provider output or user upload; only the first ~10s is edited). Mutually exclusive with previous_interaction_id. Accepts an existing, reachable HTTPS URL directly. Local paths, `file://`, `MEDIA:`, and attached media are handled by the shared media resolver when the call includes file bytes; remote-only callers that only have a path string must use a client-side resolver such as `pika-upload-file` first and pass the resulting HTTPS URL.",
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "object",
                "propertyNames": {
                  "type": "string"
                },
                "additionalProperties": {},
                "description": "Media reference object. For small inline uploads up to 3145728 decoded bytes, include filename, mime_type, and bytes_base64. Use upload_asset for larger files."
              }
            ]
          },
          "previous_interaction_id": {
            "description": "interaction_id from a prior omni result (generate_video_edit or generate_reference_video provider=omni). Continues the conversational edit chain server-side without re-uploading.",
            "type": "string",
            "minLength": 1
          },
          "reference_images": {
            "description": "Optional visual reference images for the edit (up to 6). Use `<IMAGE_REF_0>`, `<IMAGE_REF_1>`, etc. in the prompt to bind a style, product, or character reference. These images guide the edit and are NOT used as start frames. Accepts an existing, reachable HTTPS URL directly. Local paths, `file://`, `MEDIA:`, and attached media are handled by the shared media resolver when the call includes file bytes; remote-only callers that only have a path string must use a client-side resolver such as `pika-upload-file` first and pass the resulting HTTPS URL.",
            "maxItems": 6,
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "minLength": 1
                },
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {},
                  "description": "Media reference object. For small inline uploads up to 3145728 decoded bytes, include filename, mime_type, and bytes_base64. Use upload_asset for larger files."
                }
              ]
            }
          },
          "background": {
            "description": "Run in background: if true, return {task_id, status:\"running\"} immediately so the caller can poll task_status({task_id}) later. Useful when the user wants to keep chatting / doing other work while this renders. If false or omitted, blocks up to 260s and returns the inline result. Default: false.",
            "type": "boolean"
          },
          "confirm_token": {
            "description": "Confirmation token returned by a prior cost_confirmation_required response. Re-call the same tool with the exact same arguments plus this token only after the user approves the surfaced cost estimate.",
            "type": "string"
          }
        },
        "required": [
          "prompt"
        ]
      },
      "expected": "other"
    },
    {
      "provider": "pika",
      "name": "generate_keyframes_video",
      "description": "Generate a video transitioning between two keyframe images. Uses pika-api/generate/2.2/pikaframes (model pika-2.2-pikaframes).\n\nReturns the result inline when complete (typically 30s–5min). Progress updates are sent as notifications during execution. If the server budget expires before completion, falls back to `{ task_id, status }` — then call `task_status(task_id)` in a tight loop (no Bash, no sleep) until status is `completed`, `failed`, or `cancelled`.",
      "inputSchema": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "first_frame": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "object",
                "propertyNames": {
                  "type": "string"
                },
                "additionalProperties": {},
                "description": "Media reference object. For small inline uploads up to 3145728 decoded bytes, include filename, mime_type, and bytes_base64. Use upload_asset for larger files."
              }
            ],
            "description": "First keyframe image URL. Accepts an existing, reachable HTTPS URL directly. Local paths, `file://`, `MEDIA:`, and attached media are handled by the shared media resolver when the call includes file bytes; remote-only callers that only have a path string must use a client-side resolver such as `pika-upload-file` first and pass the resulting HTTPS URL."
          },
          "last_frame": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "object",
                "propertyNames": {
                  "type": "string"
                },
                "additionalProperties": {},
                "description": "Media reference object. For small inline uploads up to 3145728 decoded bytes, include filename, mime_type, and bytes_base64. Use upload_asset for larger files."
              }
            ],
            "description": "Last keyframe image URL. Accepts an existing, reachable HTTPS URL directly. Local paths, `file://`, `MEDIA:`, and attached media are handled by the shared media resolver when the call includes file bytes; remote-only callers that only have a path string must use a client-side resolver such as `pika-upload-file` first and pass the resulting HTTPS URL."
          },
          "prompt": {
            "description": "Transition prompt — motion between frames.",
            "type": "string"
          },
          "negative_prompt": {
            "description": "Negative prompt — what to avoid.",
            "type": "string"
          },
          "duration": {
            "description": "Output duration in seconds (5 or 10; default 5).",
            "anyOf": [
              {
                "type": "number",
                "const": 5
              },
              {
                "type": "number",
                "const": 10
              }
            ]
          },
          "resolution": {
            "description": "Output resolution (default 720p).",
            "type": "string",
            "enum": [
              "720p",
              "1080p"
            ]
          },
          "seed": {
            "description": "Integer seed for reproducibility.",
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "background": {
            "description": "Run in background: if true, return {task_id, status:\"running\"} immediately so the caller can poll task_status({task_id}) later. Useful when the user wants to keep chatting / doing other work while this renders. If false or omitted, blocks up to 260s and returns the inline result. Default: false.",
            "type": "boolean"
          },
          "confirm_token": {
            "description": "Confirmation token returned by a prior cost_confirmation_required response. Re-call the same tool with the exact same arguments plus this token only after the user approves the surfaced cost estimate.",
            "type": "string"
          }
        },
        "required": [
          "first_frame",
          "last_frame"
        ]
      },
      "expected": "image"
    },
    {
      "provider": "pollo",
      "name": "pollo_generate_video",
      "description": "Create a video generation task (text/image/reference-to-video depending on input fields). Any image/video input field must be a public HTTPS URL (this remote server cannot read local files). Videos take a few minutes. Returns { taskId, status } and mounts a live detail UI that polls itself and updates in place when the video is ready — on MCP-Apps hosts do NOT poll or call any status/detail tool, just reply with a brief one-line confirmation. On hosts without MCP Apps, poll pollo_get_generation_status until done. If the account is out of credits, this returns a recharge prompt that renders a Buy-credits UI instead of erroring — relay the returned text verbatim (it already carries the correct link, and the Retry button lives on the card), and do NOT add a recharge/pricing link of your own or state any credit amounts.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "brand": {
            "type": "string"
          },
          "model": {
            "type": "string"
          },
          "input": {
            "type": "object",
            "additionalProperties": {}
          },
          "webhookUrl": {
            "type": "string"
          },
          "numOutputs": {
            "type": "integer",
            "minimum": 1,
            "maximum": 4,
            "description": "generate this many outputs in one task (1-4, batch); generations[] holds all of them. Cost is billed per output."
          }
        },
        "required": [
          "brand",
          "model",
          "input"
        ],
        "additionalProperties": false,
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "expected": "video"
    },
    {
      "provider": "pollo",
      "name": "pollo_upload_image",
      "description": "Upload an image/video input for a generation. Four modes: (1) pass `browserUpload: true` with `filename` + `contentType` to get { sign, uploadKey } for a browser-direct PUT into the upload inbox — this is what the uploader widget uses (bytes never pass through the MCP channel, so there is no message-size ceiling); (2) pass `uploadKey` (and nothing else) to confirm that direct upload: the server validates it and returns { accessURL }; (3) pass `dataBase64` (a base64 data URL of the file) and the server uploads it for you, returning { accessURL } — no CORS to configure, but the bytes travel through the MCP message, so the gateway caps this at roughly 3.5 MB per file; (4) pass just `filename` to only get a presigned URL for the asset bucket: returns { sign, accessURL }, and you PUT the raw bytes to `sign` yourself (for programmatic/agent callers). Use `accessURL` as the image field in a generate tool. The remote server cannot read your local disk. Note: /file/sign may be limited to certain accounts.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "filename": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "dataBase64": {
            "type": "string"
          },
          "browserUpload": {
            "type": "boolean"
          },
          "contentType": {
            "type": "string"
          },
          "uploadKey": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "expected": "other"
    },
    {
      "provider": "runway",
      "name": "generate_multishot_video",
      "description": "Generate a multi-shot video — 3 to 5 connected scenes from a single story or per-shot prompts. Powered by Kling 3.0 (standard at 720p, pro at 1080p). No `model` parameter — resolution selects the engine.\n\nCREDIT MODE: Runway account availability is checked against the currently connected workspace.\n\nUse this when the user wants a short narrative or sequence:\n- \"a 10-second mini-story about a cat finding a friend\"\n- \"a multi-scene product ad: closeup, lifestyle, hero shot\"\n- \"transition through 3 environments: forest -> desert -> beach\"\n\nFor a single continuous shot, use `generate_video` instead. For editing/restyling an existing video, also use `generate_video` (with `referenceVideo`).\n\nREQUIRES A PAID RUNWAY WORKSPACE. On free workspaces this tool returns an account-limitation error without creating a task; do not retry.\n\nMODES:\n1. `auto` (DEFAULT) — Pass a single `storyPrompt` (or `promptText`, accepted as an alias) and the workflow plans the shots for you. Best when the user describes the *story* not the individual scenes. Example: `mode: \"auto\", storyPrompt: \"a barista discovers their cafe has been frozen in time\"`.\n2. `custom` — Pass per-shot prompts as `shots: [{prompt}, ...]` (3-5 shots). Total `duration` is divided evenly across them. Best when the user has specific ideas for each scene. Example: `mode: \"custom\", shots: [{prompt: \"wide shot of cafe\"}, {prompt: \"barista looks up, surprised\"}, {prompt: \"close on a frozen droplet of coffee\"}]`.\n\nOptional `firstSceneImage` anchors the opening frame for either mode.\n\nAvailability is checked against the current Runway workspace. Multi-shot tasks routinely take 5-10 minutes.\n\nUSER-FACING REPLIES: DO NOT mention the underlying engine (Kling 3.0 / Pro) to the user unless they explicitly ask which model was used. Talk about the multi-shot story — the scenes, transitions, and overall narrative — not the engine.\n\nParameters:\n- mode: `'auto'` (default) or `'custom'`.\n- storyPrompt: Required for `mode='auto'`. Full story / overall scene description.\n- shots: Required for `mode='custom'`. Array of `{prompt}`, 3-5 entries.\n- duration: Total seconds — `5` | `10` (default) | `15`. String values `'5'` | `'10'` | `'15'` are also accepted for backwards compatibility.\n- aspectRatio: `'16:9'` (default) | `'1:1'` | `'9:16'`. `ratio` is accepted as an alias.\n- resolution: `'720p'` (default, Kling 3.0 Standard) | `'1080p'` (Kling 3.0 Pro).\n- sound: Boolean, generate audio (default true).\n- firstSceneImage: Optional `{url, assetId?}` to anchor the first frame. If `assetId` is omitted, the URL is imported to a Runway dataset asset before submission because the multi-shot workflow requires a resolvable asset reference.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "rationale": {
            "type": "string",
            "description": "Why are you calling this tool? What is the user actually trying to accomplish? Be specific — e.g., \"user uploaded a vacation photo and asked to animate it as a 5-second clip for Instagram\"."
          },
          "mode": {
            "type": "string",
            "enum": [
              "auto",
              "custom"
            ],
            "description": "'auto' (default) or 'custom'."
          },
          "storyPrompt": {
            "type": "string",
            "description": "Required for mode='auto'. Full story or scene description. promptText is also accepted as an alias."
          },
          "promptText": {
            "type": "string",
            "description": "Alias for storyPrompt in mode='auto' for consistency with other generation tools."
          },
          "shots": {
            "type": "array",
            "description": "Required for mode='custom'. Per-shot prompts (3-5 shots).",
            "items": {
              "type": "object",
              "properties": {
                "prompt": {
                  "type": "string"
                }
              },
              "required": [
                "prompt"
              ],
              "additionalProperties": false
            },
            "minItems": 3,
            "maxItems": 5
          },
          "duration": {
            "enum": [
              "5",
              "10",
              "15",
              5,
              10,
              15
            ],
            "description": "Total duration in seconds: 5, 10 (default), or 15. String values '5', '10', and '15' are accepted for backwards compatibility."
          },
          "aspectRatio": {
            "type": "string",
            "enum": [
              "16:9",
              "1:1",
              "9:16"
            ],
            "description": "'16:9' (default), '1:1', or '9:16'. ratio is also accepted as an alias."
          },
          "ratio": {
            "type": "string",
            "enum": [
              "16:9",
              "1:1",
              "9:16"
            ],
            "description": "Alias for aspectRatio for consistency with other generation tools."
          },
          "resolution": {
            "type": "string",
            "enum": [
              "720p",
              "1080p"
            ],
            "description": "'720p' (default, Kling 3.0 Standard) or '1080p' (Kling 3.0 Pro)."
          },
          "sound": {
            "type": "boolean",
            "description": "Generate audio (default true)."
          },
          "firstSceneImage": {
            "type": "object",
            "description": "Optional first-scene anchor image.",
            "properties": {
              "url": {
                "type": "string"
              },
              "assetId": {
                "type": "string",
                "description": "Optional Runway dataset asset ID. If omitted, the MCP server imports the URL to create one before submitting."
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      },
      "expected": "video"
    },
    {
      "provider": "runway",
      "name": "generate_product_marketing_video",
      "description": "Generate a polished creative product ad video from a product URL or product image plus a campaign idea.\n\nCREDIT MODE: Runway account availability is checked against the currently connected workspace.\n\nUse this for product marketing / creative ad requests like:\n- \"Make a jewelry ad featuring a chameleon in a jewelry store\"\n- \"Turn this product page into a cinematic ad\"\n- \"Use this product image and this character reference to make a funny product commercial\"\n\nv1 supports only format: `creative_ad_video`.\n\nWorkflow:\n1. Get the exact product image from `productImages[0]` or extract the best high-resolution product image from `productUrl`.\n2. Use optional `referenceImages` as character, scene, mood, or world references.\n3. Internally generate a 3x3 storyboard image, preferring GPT Image 2 for paid workspaces and falling back to Nano Banana Pro otherwise.\n4. Use that storyboard as sequential shot guidance for Seedance 2, along with the product image and references, to create the final video.\n\nPRODUCT URL FALLBACK:\n- `productUrl` extraction is best-effort. Some ecommerce sites block automated access or hide product images behind scripts.\n- If extraction fails, do not retry the same URL or claim Runway cannot make the ad. Ask the user for a screenshot of the product page or a direct product image upload, then call this tool again with `productImages` / `productImageFile`.\n- Do not call `generate_image` with a text description of the product to create the product reference. That produces a lookalike, not the real SKU.\n- For branded/luxury products, the exact product image is required for an accurate ad. Only invent or generate a stand-in product if the user explicitly agrees that an approximate substitute is acceptable.\n\nInputs:\n- productUrl: Product landing page URL. The tool will scrape metadata and rank image candidates, preferring high-resolution product/gallery images.\n- productImages: Product image URLs from uploads, recent assets, or previous generations. Preferred over productUrl extraction.\n- productImageFile: ChatGPT-only uploaded product image file. Use this when ChatGPT provides a user-uploaded product image.\n- referenceImages: Optional character/scene/mood/world references.\n- promptText: Required creative campaign idea. If the user requests a named artist/director/photographer/studio style, describe the visual qualities instead and do not include the name.\n- duration: 10 by default; use 15 only when the user asks for a longer ad.\n\nSTYLE SAFETY: Do not include names of artists, directors, photographers, studios, or other creators anywhere in prompts submitted to Runway tasks. When style direction is needed, translate it into camera language, palette, lighting, genre, era, composition, and material texture.\n\nUSER-FACING REPLIES: DO NOT mention internal model names unless asked. Do not mention the intermediate storyboard unless useful. Tell the user the creative ad video is generating and the viewer will update when ready.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "rationale": {
            "type": "string",
            "description": "Why are you calling this tool? What is the user actually trying to accomplish? Be specific — e.g., \"user uploaded a vacation photo and asked to animate it as a 5-second clip for Instagram\"."
          },
          "productUrl": {
            "type": "string",
            "description": "Product landing page URL. Used only if productImages is empty."
          },
          "productImages": {
            "type": "array",
            "description": "Product image URLs [{url, tag}]. Preferred over productUrl extraction.",
            "items": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                },
                "tag": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ],
              "additionalProperties": false
            }
          },
          "productImageFile": {
            "type": "object",
            "description": "ChatGPT-only file param for a user-uploaded product image. Prefer productImages when you already have a public or Runway-hosted URL.",
            "properties": {
              "download_url": {
                "type": "string",
                "description": "Temporary ChatGPT file download URL."
              },
              "file_id": {
                "type": "string",
                "description": "ChatGPT file ID."
              },
              "mime_type": {
                "type": "string",
                "description": "MIME type, e.g. image/png."
              },
              "file_name": {
                "type": "string",
                "description": "Original file name."
              }
            },
            "required": [
              "download_url",
              "file_id"
            ],
            "additionalProperties": false
          },
          "referenceImages": {
            "type": "array",
            "description": "Optional character, scene, mood, or world reference image URLs [{url, tag}].",
            "items": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                },
                "tag": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ],
              "additionalProperties": false
            }
          },
          "promptText": {
            "type": "string",
            "description": "Required creative ad idea. If the user requests a named artist/director/photographer/studio style, describe the visual qualities instead and do not include the name."
          },
          "format": {
            "type": "string",
            "enum": [
              "creative_ad_video"
            ],
            "description": "Only supported value in v1: creative_ad_video."
          },
          "duration": {
            "type": "number",
            "enum": [
              10,
              15
            ],
            "description": "Final video duration. Default 10. Use 15 only when the user asks for longer."
          },
          "storyboardImage": {
            "type": "object",
            "description": "Internal continuation only: completed storyboard image from the first workflow stage.",
            "properties": {
              "url": {
                "type": "string"
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          },
          "productMetadata": {
            "type": "object",
            "description": "Internal continuation only: product URL metadata.",
            "properties": {
              "url": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "image": {
                "type": "object",
                "description": "Backward-compatible continuation metadata from older storyboard responses. Ignored by the handler; productImages[0] is the canonical product image.",
                "properties": {
                  "url": {
                    "type": "string"
                  },
                  "width": {
                    "type": "number"
                  },
                  "height": {
                    "type": "number"
                  },
                  "alt": {
                    "type": "string"
                  },
                  "source": {
                    "type": "string"
                  },
                  "score": {
                    "type": "number"
                  }
                },
                "additionalProperties": false
              }
            },
            "additionalProperties": false
          }
        },
        "required": [
          "promptText"
        ],
        "additionalProperties": false
      },
      "expected": "video"
    },
    {
      "provider": "runway",
      "name": "remove_image_background",
      "description": "Remove the background from an image: SAM3 segmentation isolates the subject you describe and outputs a PNG with a TRANSPARENT background (alpha channel) — the subject is kept, everything else is removed.\n\nCREDIT MODE: Runway account availability is checked against the currently connected workspace.\n\nWHEN TO USE THIS:\n- \"remove the background\", \"cut out the person/product\", \"make the background transparent\", \"isolate the subject\", \"give me a sticker/cutout of X\".\n- NOT for replacing the background with new content or other edits (use `generate_image` with referenceImages), NOT for upscaling (`upscale_image`). For videos use `remove_video_background`.\n\nSOURCE IMAGE CONSTRAINTS: at most 4096px per side. Cost: 1 credit per image. If the subject can't be found in the image the task fails with \"No detections found\" — rephrase the subject and retry once, then tell the user what couldn't be found.\n\nOUTPUT: a PNG with an alpha channel (true transparency).\n\nHANDLING USER ATTACHMENTS:\n- ChatGPT: pass an uploaded image as `imageFile`; the tool imports it server-side. NEVER pass local paths like /mnt/data/... as `image.url`.\n- Claude/Cursor/local agents: upload local files first via `init_upload` -> curl -> `complete_upload`, then pass the returned asset URL as `image.url`. Outputs of `generate_image` can be passed directly as `image.url`.\n\nUSER-FACING REPLIES: Talk about the cutout (what's being isolated and that the background becomes transparent), not the model or task machinery. Do not mention SAM3 unless the user asks.\n\nParameters:\n- subject: Required. What to KEEP, described in a few words (e.g. \"the person\", \"the sneaker\", \"the dog on the left\"). Max 200 characters.\n- image: `{url}` — source image. URL must be a Runway-hosted asset URL (from complete_upload or generate_image) or a public HTTPS image URL.\n- imageFile: ChatGPT-only uploaded image file param `{download_url, file_id, mime_type, file_name}`.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "rationale": {
            "type": "string",
            "description": "Why are you calling this tool? What is the user actually trying to accomplish? Be specific — e.g., \"user uploaded a vacation photo and asked to animate it as a 5-second clip for Instagram\"."
          },
          "subject": {
            "type": "string",
            "description": "What to KEEP in the image, in a few words (e.g. \"the person\"). Max 200 characters.",
            "maxLength": 200
          },
          "image": {
            "type": "object",
            "description": "Source image. URL must be a Runway-hosted asset URL (complete_upload or generate_image output) or a public HTTPS image URL. Do not pass ChatGPT local paths like /mnt/data/...; use imageFile instead.",
            "properties": {
              "url": {
                "type": "string",
                "description": "Runway-hosted asset URL (preferred) or public HTTPS image URL. Never use /mnt/data or other local file paths here."
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          },
          "imageFile": {
            "type": "object",
            "description": "ChatGPT-only file param for a user-uploaded source image. Prefer image.url when you already have a Runway-hosted or public URL.",
            "properties": {
              "download_url": {
                "type": "string",
                "description": "Temporary ChatGPT file download URL."
              },
              "file_id": {
                "type": "string",
                "description": "ChatGPT file ID."
              },
              "mime_type": {
                "type": "string",
                "description": "MIME type, e.g. image/png."
              },
              "file_name": {
                "type": "string",
                "description": "Original file name."
              }
            },
            "required": [
              "download_url",
              "file_id"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "subject"
        ],
        "additionalProperties": false
      },
      "expected": "other"
    },
    {
      "provider": "runway",
      "name": "upscale_image",
      "description": "Upscale an existing image to a higher resolution (2x, 4x, 8x, or 16x) using Runway's AI image upscaler. Use this to sharpen, denoise, and increase the resolution of an image — it does NOT change the content, composition, or style; for those edits use `generate_image` with `referenceImages`.\n\nCREDIT MODE: Runway account availability is checked against the currently connected workspace.\n\nPAID PLAN REQUIRED: This upscaler is not available on free Runway workspaces. If the connected workspace is on a free plan the task will be rejected with an account-limitation message — tell the user image upscaling isn't available in their current workspace and do not retry. There is no free upscaling alternative; do NOT try to fake an upscale with `generate_image`.\n\nWHEN TO USE:\n- The user wants a low-res / soft / blurry / grainy image made crisper or larger (e.g. \"upscale this to 4x\", \"make this image higher resolution\", \"enhance / denoise this photo\").\n- The user has a finished image (their own upload, or an output from `generate_image`) and wants a higher-fidelity version of the exact same image.\n\nWHEN NOT TO USE:\n- To restyle, edit, remove/replace backgrounds or objects, or otherwise change the content → use `generate_image` with `referenceImages[0]`.\n- To generate a brand-new image → use `generate_image`.\n- To upscale a video → use `upscale_video`.\n\nINPUT:\n- Provide the source image as `image.url`: a Runway-hosted URL (from `complete_upload` or a `generate_image` output) or a public HTTPS image URL. The tool imports it into Runway automatically.\n- Pass `image.width`/`image.height` when known so scale-factor limits can be checked before submitting. The input must be at least 300x300px, and the output (width * scaleFactor x height * scaleFactor) must stay under ~25 megapixels — e.g. a 4000x3000 image only supports 1 step of 2x.\n\nFLAVOR / SCALE RULES:\n- flavor `sublime` (DEFAULT — artistic/illustrated images, smooth gradients, vibrant colors): scaleFactor 2, 4, 8, or 16.\n- flavor `photo` (photographic images, natural colors, realistic detail): scaleFactor 2 only.\n- flavor `photo_denoiser` (noise reduction for low-light/grainy photos): scaleFactor 2 only.\n\nHANDLING USER ATTACHMENTS:\n- Claude/Cursor/local agents: if the user attached a local image, run `init_upload` -> curl -> `complete_upload` first, then pass the returned URL as `image.url`.\n- ChatGPT: if it supplies an uploaded image as `imageFile`, pass it directly. NEVER pass local paths such as `/mnt/data/file.png` as `image.url`; use `imageFile` instead.\n\nUSER-FACING REPLIES: Talk about the result (\"upscaling your image 4x\"), not the underlying engine. Do not mention the model/provider unless the user explicitly asks.\n\nParameters:\n- image: `{ url, width?, height? }` — the source image to upscale. URL must be public HTTPS or Runway-hosted. Do NOT use ChatGPT local paths like `/mnt/data/...`; use `imageFile` for ChatGPT uploads.\n- imageFile: ChatGPT-only uploaded image file param `{download_url, file_id, mime_type, file_name}`.\n- scaleFactor: 2, 4, 8, or 16. Default: 2. Factors above 2 require flavor `sublime`.\n- flavor: `sublime` | `photo` | `photo_denoiser`. Default: `sublime`. Pick `photo` for photographs, `photo_denoiser` for grainy/low-light photos.\n- sharpen: 0-100. Default: 10. Higher = crisper edges.\n- smartGrain: 0-100. Default: 10. Adds natural film-like grain to avoid a plasticky look.\n- ultraDetail: 0-100. Default: 30. Higher = more invented micro-detail (can drift from the source).",
      "inputSchema": {
        "type": "object",
        "properties": {
          "rationale": {
            "type": "string",
            "description": "Why are you calling this tool? What is the user actually trying to accomplish? Be specific — e.g., \"user uploaded a vacation photo and asked to animate it as a 5-second clip for Instagram\"."
          },
          "image": {
            "type": "object",
            "description": "Source image to upscale. URL must be a public HTTPS image URL or a Runway-hosted URL (complete_upload or generate_image output). Do not pass ChatGPT local paths like /mnt/data/...; use imageFile instead.",
            "properties": {
              "url": {
                "type": "string",
                "description": "Public HTTPS or Runway-hosted image URL. Never use /mnt/data or other local file paths here."
              },
              "width": {
                "type": "number",
                "description": "Source image width in pixels. Pass when known so scale-factor limits are validated up front."
              },
              "height": {
                "type": "number",
                "description": "Source image height in pixels. Pass when known so scale-factor limits are validated up front."
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          },
          "imageFile": {
            "type": "object",
            "description": "ChatGPT-only file param for a user-uploaded source image. Prefer image.url when you already have a public or Runway-hosted URL.",
            "properties": {
              "download_url": {
                "type": "string",
                "description": "Temporary ChatGPT file download URL."
              },
              "file_id": {
                "type": "string",
                "description": "ChatGPT file ID."
              },
              "mime_type": {
                "type": "string",
                "description": "MIME type, e.g. image/png."
              },
              "file_name": {
                "type": "string",
                "description": "Original file name."
              }
            },
            "required": [
              "download_url",
              "file_id"
            ],
            "additionalProperties": false
          },
          "scaleFactor": {
            "type": "number",
            "description": "Upscale factor. Default: 2. Factors above 2 require flavor 'sublime'.",
            "enum": [
              2,
              4,
              8,
              16
            ]
          },
          "flavor": {
            "type": "string",
            "description": "Upscaling flavor. Default: 'sublime'. 'sublime' for artistic/illustrated images, 'photo' for photographs, 'photo_denoiser' for grainy/low-light photos.",
            "enum": [
              "sublime",
              "photo",
              "photo_denoiser"
            ]
          },
          "sharpen": {
            "type": "number",
            "description": "Sharpening strength 0-100. Default: 10."
          },
          "smartGrain": {
            "type": "number",
            "description": "Film-grain strength 0-100. Default: 10."
          },
          "ultraDetail": {
            "type": "number",
            "description": "Invented micro-detail strength 0-100. Default: 30."
          }
        },
        "additionalProperties": false
      },
      "expected": "other"
    },
    {
      "provider": "runway",
      "name": "edit_video",
      "description": "Edit an existing video with Runway's Aleph 2.0 in-context video editor: it changes ONLY what you ask for and preserves everything else — subjects, motion, framing, timing, background, lighting.\n\nCREDIT MODE: Runway account availability is checked against the currently connected workspace.\n\nWHEN TO USE THIS vs generate_video:\n- USE edit_video (this tool) for targeted, surgical edits of existing footage where preservation matters: \"make the sneakers red\", \"change the outfit to a yellow fur coat\", \"remove the items on the wall behind her\", \"add graffiti on the wall\", \"change the season to winter\", \"relight the scene\", \"make it dark anime style\" — or whenever the user mentions Aleph or Edit Studio.\n- USE generate_video with referenceVideo (seedance-2) when the source video is more of a loose reference: motion transfer, using the clip as style/structure inspiration, or heavy re-imagining where preserving the original isn't the point. Also fall back to it when the source violates Aleph's constraints (see below), or when an Aleph result was unsatisfying — and suggest edit_video when a seedance v2v edit changed more than the user wanted.\n- USE expand_video to change the video's ASPECT RATIO by outpainting beyond the frame edges (\"make it vertical\", \"uncrop\", \"convert to 21:9\") — this tool edits content within the frame, expand_video grows the frame.\n\nSOURCE VIDEO CONSTRAINTS (Aleph 2.0): 2-30 seconds, up to 1080p, up to 30fps, at most 10 cuts/shot changes, conventional aspect ratio. Cost: 28 credits/second of source (56 credit minimum), so a wasted submission is expensive — that's why the keyframe preview checkpoint below is the default.\n\nHOW THE WORKFLOW WORKS (a keyframe-driven edit is much higher quality than a text-only one):\n1. CANDIDATES — call with `promptText` + `video` only (video.durationSeconds required for this stage). The tool extracts ~4 evenly spaced frames from the video and returns them inline with their timestamps. LOOK at the frames and pick the one that most clearly shows the edit target (e.g. the widest shot for a background change; a close-up of the subject for a detail change). You may also pick your own timestamp if none fit.\n2. KEYFRAME PREVIEW — call again with the SAME arguments plus `keyframeTimestampSeconds`. The tool extracts that exact frame, edits it with an image model to apply your change, and returns the edited keyframe inline. SHOW it to the user and ask if they're happy before continuing (this is the default checkpoint). If they want a different look, re-call with a refined `promptText` or a different timestamp.\n3. SUBMIT — once approved, call again with `keyframeImage.url` set to the edited keyframe URL and the SAME `keyframeTimestampSeconds`. The tool submits the Aleph 2.0 video edit task; the result arrives via the inline viewer / `get_task`.\n\nSHORTCUTS:\n- If the user has said they want to skip the preview/approval step, pass `skipPreview: true` at step 2 — the tool generates the keyframe AND submits the video edit in one call.\n- If the user supplies their own already-edited frame, pass it directly as `keyframeImage.url` with the timestamp it came from.\n- `textOnly: true` submits a text-prompt-only edit with no keyframe — lower quality, but a valid fallback when frame extraction or the keyframe edit fails.\n\nPROMPTING (Aleph 2.0 guide): simple, targeted prompts work best — an action verb (add, remove, change, replace, re-light, re-style) plus the desired transformation, e.g. \"change the outfit and bag to soft yellow\". Because Aleph only changes what you ask for, precise language beats long descriptions. Use `extraMotionPrompt` ONLY for motion that isn't implied by the keyframe or the original video (e.g. \"fire begins to spread up the trees\") — most edits don't need it.\n\nHANDLING USER ATTACHMENTS:\n- ChatGPT: pass an uploaded video as `videoFile`; the tool imports it server-side. NEVER pass local paths like /mnt/data/... as `video.url`.\n- Claude/Cursor/local agents: upload local files first via `init_upload` -> curl -> `complete_upload`, then pass the returned asset URL as `video.url`.\n- ALWAYS pass `video.durationSeconds` when you know it (from file metadata) — the candidates stage requires it, and it makes credit accounting accurate.\n\nUSER-FACING REPLIES: Talk about the edit (what's changing in the video), not the model or task machinery. Do not mention model names unless the user asks.\n\nParameters:\n- promptText: Required. The edit instruction — what to change; everything else is preserved.\n- video: `{url, durationSeconds}` — source video. URL must be a Runway-hosted /datasets/ asset URL (from complete_upload) or a public HTTPS video URL.\n- videoFile: ChatGPT-only uploaded video file param `{download_url, file_id, mime_type, file_name}`.\n- keyframeTimestampSeconds: Timestamp (seconds) of the frame that anchors the edit. Must be within the video duration. Setting this triggers the keyframe edit + preview stage.\n- keyframeImage: `{url}` — an ALREADY-EDITED keyframe image (from step 2's preview, or user-supplied). Requires `keyframeTimestampSeconds`. Setting this submits the video edit.\n- keyframeModel: Image model for the keyframe edit. One of `nano-banana-pro`, `nano-banana-2`, `nano-banana-2-lite`, `gpt-image-2`, `seedream-5`, `ideogram-4`, `grok-imagine-image-2`, `gen-4`, `gen-4-image-turbo`. Default: `nano-banana-pro`.\n- extraMotionPrompt: Optional motion instruction for motion that isn't implied by the keyframe or original video.\n- skipPreview: When true at the keyframe stage, submit the video edit immediately after generating the keyframe instead of pausing for approval. Only use when the user has explicitly opted to skip the check.\n- textOnly: Submit a text-prompt-only edit with no keyframe (lower quality fallback).",
      "inputSchema": {
        "type": "object",
        "properties": {
          "rationale": {
            "type": "string",
            "description": "Why are you calling this tool? What is the user actually trying to accomplish? Be specific — e.g., \"user uploaded a vacation photo and asked to animate it as a 5-second clip for Instagram\"."
          },
          "promptText": {
            "type": "string",
            "description": "Required. The edit instruction — action verb + desired change, e.g. \"make the sneakers red\", \"remove the items on the wall behind her\", \"change the season to winter\". Everything not described is preserved."
          },
          "video": {
            "type": "object",
            "description": "Source video to edit. URL must be a Runway-hosted /datasets/<UUID>.<ext> URL from complete_upload or a public HTTPS URL. Do not pass ChatGPT local paths like /mnt/data/...; use videoFile instead.",
            "properties": {
              "url": {
                "type": "string",
                "description": "Runway-hosted dataset URL (preferred) or public HTTPS video URL. Never use /mnt/data or other local file paths here."
              },
              "durationSeconds": {
                "type": "number",
                "description": "Source video duration in seconds (2-30 supported). ALWAYS pass when known — required for the candidate-frames stage and used for accurate credit accounting."
              },
              "assetId": {
                "type": "string",
                "description": "Runway dataset asset id for the source video. Do NOT invent this. The candidate/preview stages return a resolved `video` object that includes it — pass that object back verbatim on the follow-up calls so the tool reuses the registered dataset instead of re-uploading the video."
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          },
          "videoFile": {
            "type": "object",
            "description": "ChatGPT-only file param for a user-uploaded source video. Prefer video.url when you already have a Runway-hosted or public URL.",
            "properties": {
              "download_url": {
                "type": "string",
                "description": "Temporary ChatGPT file download URL."
              },
              "file_id": {
                "type": "string",
                "description": "ChatGPT file ID."
              },
              "mime_type": {
                "type": "string",
                "description": "MIME type, e.g. video/mp4."
              },
              "file_name": {
                "type": "string",
                "description": "Original file name."
              }
            },
            "required": [
              "download_url",
              "file_id"
            ],
            "additionalProperties": false
          },
          "keyframeTimestampSeconds": {
            "type": "number",
            "description": "Timestamp (seconds) in the source video of the frame that anchors the edit. Pick it from the candidate frames this tool returns (or choose your own). Must be less than the video duration. Reuse the SAME value when later passing keyframeImage."
          },
          "keyframeImage": {
            "type": "object",
            "description": "An already-edited keyframe image — typically the preview URL returned by the keyframe stage, after user approval. Requires keyframeTimestampSeconds (the timestamp the frame was extracted at). Setting this submits the Aleph video edit.",
            "properties": {
              "url": {
                "type": "string",
                "description": "Edited keyframe image URL (Runway-hosted or public HTTPS)."
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          },
          "keyframeModel": {
            "type": "string",
            "description": "Image model used to edit the keyframe. Default: nano-banana-pro.",
            "enum": [
              "nano-banana-pro",
              "nano-banana-2",
              "nano-banana-2-lite",
              "gpt-image-2",
              "seedream-5",
              "ideogram-4",
              "grok-imagine-image-2",
              "gen-4",
              "gen-4-image-turbo"
            ]
          },
          "extraMotionPrompt": {
            "type": "string",
            "description": "Optional motion instruction for motion that is NOT implied by the keyframe or the original video (e.g. \"fire begins to spread up the trees\"). Most edits do not need this."
          },
          "skipPreview": {
            "type": "boolean",
            "description": "When true at the keyframe stage, submit the video edit immediately after generating the edited keyframe (no approval pause). Only set when the user explicitly opted to skip the preview."
          },
          "textOnly": {
            "type": "boolean",
            "description": "Submit a text-prompt-only edit with no keyframe. Lower quality — use as a fallback when the keyframe workflow is not possible."
          }
        },
        "required": [
          "promptText"
        ],
        "additionalProperties": false
      },
      "expected": "other"
    }
  ];

function tool(name: string, properties: Record<string, unknown> = {}): RemoteMcpToolLike {
  return {
    name,
    inputSchemaJson: JSON.stringify({ type: "object", properties }),
  };
}

describe("classifyRemoteMcpTool", () => {
  it.each([
    ["generate_image", "image"],
    ["create-photo", "image"],
    ["text_to_image", "image"],
    ["generate_video", "video"],
    ["createMovie", "video"],
    ["image_to_video", "video"],
    ["text-to-video", "video"],
  ] as const)("%s を %s 生成へ分類する", (name, expected) => {
    expect(classifyRemoteMcpTool(tool(name))).toBe(expected);
  });

  it("汎用 generate は schema の媒体フィールドで分類する", () => {
    expect(
      classifyRemoteMcpTool(tool("generate", { video_prompt: { type: "string" } })),
    ).toBe("video");
    expect(
      classifyRemoteMcpTool(tool("create", { image_prompt: { type: "string" } })),
    ).toBe("image");
  });

  it("媒体名があっても一覧・削除は生成扱いにしない", () => {
    expect(classifyRemoteMcpTool(tool("list_image_models"))).toBe("other");
    expect(classifyRemoteMcpTool(tool("delete_video"))).toBe("other");
  });

  it("画像と動画の両方が候補になる汎用生成は推測せずその他にする", () => {
    expect(
      classifyRemoteMcpTool(
        tool("generate_asset", { output_type: { type: "string", enum: ["image", "video"] } }),
      ),
    ).toBe("other");
  });

  it("Kling の実測 text_to_image は説明と schema に動画語があっても画像生成へ分類する", () => {
    expect(
      classifyRemoteMcpTool({
        name: "text_to_image",
        description: "Generate images from a text prompt with Kling AI. Call who_am_i first to discover the available models and each model's argument specification. Returns a generation_id immediately; poll query_tasks for the image URLs.- If user intent or any parameter is uncertain, ask first. Every job is charged; do not submit trial jobs.- If user uses alias words, map to canonical names and pass canonical only. Do not invent names or value.- On timeout/long hang/failure/unexpected result, keep user informed. Ask user whether to retry or change parameters. Do not auto-resubmit or silently change intent/parameters. Soft constraint: text_to_image does NOT support subjects (Elements) at all — neither image nor video subjects. Never pass an 'elements' argument or a <<<id>>> subject binding here. If the user wants to generate with a subject, use image_to_image (image subject) or image_to_video (video subject) instead.",
        inputSchemaJson: JSON.stringify({
          type: "object",
          properties: {
            model: {
              type: "string",
              description: "Model to use; must be one of the models listed for this tool in who_am_i's availableModels. Required: there is no default model. Call who_am_i first and choose the model whose description best fits the user's request.",
            },
            arguments: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  value: { type: "string" },
                },
                required: ["name", "value"],
              },
              description: "Generation arguments as name/value pairs, e.g. [{\"name\": \"prompt\", \"value\": \"a cat\"}]. All values are strings. Required names, defaults and allowed values are declared per model in who_am_i.",
            },
            inputs: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  inputType: { type: "string" },
                  name: { type: "string" },
                  url: { type: "string" },
                },
                required: ["inputType", "name", "url"],
              },
              description: "Resource inputs as declared per model in who_am_i; each item is {name, inputType: 'URL', url}. Omit when the chosen model declares no inputs.",
            },
            rationale: {
              type: "string",
              description: "Detailed purpose explaining the user's core objective for invoking this tool, including contextual reasoning behind parameter selections. Example: \"User uploaded a personal artwork image and requested a short animated clip for personal sharing; resolution set to 4K per explicit user demand for maximum visual clarity\".",
            },
            taskTraceId: {
              type: "string",
              description: "RFC 4122 UUID V7 identifier to group consecutive, logically connected operations under one user task intent. The same ID is reused for chained steps completing a single goal, such as generating an image then converting it to video for the same subject. A fresh unique UUID must be assigned once the user switches to an unrelated new task, isolating execution traces across distinct requests.",
            },
          },
          required: [],
          additionalProperties: false,
        }),
      }),
    ).toBe("image");
  });

  it("Pollo の実測 pollo_generate_video は画像語を含む説明でも動画生成へ分類する", () => {
    expect(
      classifyRemoteMcpTool({
        name: "pollo_generate_video",
        description: "Create a video generation task (text/image/reference-to-video depending on input fields). Any image/video input field must be a public HTTPS URL (this remote server cannot read local files). Videos take a few minutes. Returns { taskId, status } and mounts a live detail UI that polls itself and updates in place when the video is ready — on MCP-Apps hosts do NOT poll or call any status/detail tool, just reply with a brief one-line confirmation. On hosts without MCP Apps, poll pollo_get_generation_status until done. If the account is out of credits, this returns a recharge prompt that renders a Buy-credits UI instead of erroring — relay the returned text verbatim (it already carries the correct link, and the Retry button lives on the card), and do NOT add a recharge/pricing link of your own or state any credit amounts.",
        inputSchemaJson: JSON.stringify({
          type: "object",
          properties: {
            brand: { type: "string" },
            model: { type: "string" },
            input: { type: "object", additionalProperties: {} },
            webhookUrl: { type: "string" },
            numOutputs: {
              type: "integer",
              minimum: 1,
              maximum: 4,
              description: "generate this many outputs in one task (1-4, batch); generations[] holds all of them. Cost is billed per output.",
            },
          },
          required: ["brand", "model", "input"],
          additionalProperties: false,
          $schema: "http://json-schema.org/draft-07/schema#",
        }),
      }),
    ).toBe("video");
  });

  it("元動画必須の video_to_video は生成候補へ入れない", () => {
    expect(
      classifyRemoteMcpTool({
        name: "video_to_video",
        description: "Generate a new video from an existing video.",
        inputSchemaJson: JSON.stringify({
          type: "object",
          properties: {
            prompt: { type: "string" },
            source_video: { type: "string" },
          },
          required: ["prompt", "source_video"],
        }),
      }),
    ).toBe("other");
  });

  it("生成動詞の無い upscale_video は生成候補へ入れない", () => {
    expect(
      classifyRemoteMcpTool({
        name: "upscale_video",
        description: "Upscale and enhance an existing video.",
        inputSchemaJson: JSON.stringify({ type: "object", properties: {} }),
      }),
    ).toBe("other");
  });


  it.each(MEASURED_CLASSIFICATION_FIXTURES)(
    "$provider $name の実測分類を $expected に固定する",
    ({ name, description, inputSchema, expected }) => {
      expect(
        classifyRemoteMcpTool({
          name,
          description,
          inputSchemaJson: JSON.stringify(inputSchema),
        }),
      ).toBe(expected);
    },
  );

  it("3分類の配列を作る", () => {
    const groups = groupRemoteMcpTools([
      tool("generate_image"),
      tool("generate_video"),
      tool("account_balance"),
    ]);
    expect(groups.image.map((item) => item.name)).toEqual(["generate_image"]);
    expect(groups.video.map((item) => item.name)).toEqual(["generate_video"]);
    expect(groups.other.map((item) => item.name)).toEqual(["account_balance"]);
  });
});

describe("buildRemoteMcpParams", () => {
  it("代表フィールドへプロンプト・モデル・比率・枚数を割り当てる", () => {
    const result = buildRemoteMcpParams(
      JSON.stringify({
        type: "object",
        properties: {
          prompt: { type: "string" },
          model: { type: "string" },
          aspect_ratio: { type: "string" },
          n: { type: "integer" },
        },
        required: ["prompt", "model", "aspect_ratio", "n"],
      }),
      { prompt: "白いお餅", model: "krea-1", aspectRatio: "16:9", count: 2 },
    );

    expect(result.params).toEqual({
      prompt: "白いお餅",
      model: "krea-1",
      aspect_ratio: "16:9",
      n: 2,
    });
    expect(JSON.parse(result.paramsJson)).toEqual(result.params);
    expect(result.missingRequired).toEqual([]);
  });

  it("別名 text/model_id/resolution/num_images にも割り当てる", () => {
    const result = buildRemoteMcpParams(
      JSON.stringify({
        properties: {
          text: { type: "string" },
          model_id: { type: "string" },
          resolution: { type: "string" },
          num_images: { type: "string" },
        },
        required: ["text"],
      }),
      { prompt: "湯気の立つ餅", model: "m-2", aspectRatio: "1:1", count: 3 },
    );
    expect(result.params).toEqual({
      text: "湯気の立つ餅",
      model_id: "m-2",
      resolution: "1:1",
      num_images: "3",
    });
  });

  it("model系の欄が無い場合は Magnific 互換の mode へモデルを渡す", () => {
    const result = buildRemoteMcpParams(
      JSON.stringify({
        properties: {
          prompt: { type: "string" },
          mode: { type: "string", enum: ["video-a", "video-b"] },
        },
        required: ["prompt", "mode"],
      }),
      { prompt: "scene", model: "video-b" },
    );
    expect(result.params).toEqual({ prompt: "scene", mode: "video-b" });
    expect(result.missingRequired).toEqual([]);
  });

  it("動画の尺・開始終了画像・参照素材を明示された欄へ割り当てる", () => {
    const result = buildRemoteMcpParams(
      JSON.stringify({
        properties: {
          prompt: { type: "string" },
          model: { type: "string" },
          duration_seconds: { type: "integer" },
          first_frame: { type: "string" },
          last_frame: { type: "string" },
          reference_images: { type: "array", items: { type: "string" } },
          reference_videos: { type: "array", items: { type: "string" } },
          motion_references: { type: "array", items: { type: "string" } },
        },
        required: ["prompt", "model"],
      }),
      {
        prompt: "お餅がゆっくり膨らむ",
        model: "video-1",
        durationSeconds: 8,
        startImagePath: "/tmp/start.png",
        endImagePath: "/tmp/end.png",
        referenceImagePaths: ["/tmp/ref-1.png", "/tmp/ref-2.png"],
        referenceVideoPaths: ["/tmp/ref.mov"],
        motionReferencePaths: ["/tmp/motion.mp4"],
      },
    );
    expect(result.params).toEqual({
      prompt: "お餅がゆっくり膨らむ",
      model: "video-1",
      duration_seconds: 8,
      first_frame: "/tmp/start.png",
      last_frame: "/tmp/end.png",
      reference_images: ["/tmp/ref-1.png", "/tmp/ref-2.png"],
      reference_videos: ["/tmp/ref.mov"],
      motion_references: ["/tmp/motion.mp4"],
    });
    expect(result.missingRequired).toEqual([]);
  });

  it("params ラッパー内のモデル欄と入力欄へ割り当てる", () => {
    const result = buildRemoteMcpParams(
      JSON.stringify({
        properties: {
          params: {
            type: "object",
            properties: {
              prompt: { type: "string" },
              model_id: { type: "string" },
              aspect_ratio: { type: "string" },
            },
            required: ["prompt", "model_id"],
          },
        },
        required: ["params"],
      }),
      { prompt: "scene", model: "m-3", aspectRatio: "9:16" },
    );
    expect(result.params).toEqual({
      params: { prompt: "scene", model_id: "m-3", aspect_ratio: "9:16" },
    });
    expect(result.missingRequired).toEqual([]);
    expect(remoteMcpSchemaHasModelField(JSON.stringify({
      properties: { params: { type: "object", properties: { model: { type: "string" } } } },
    }))).toBe(true);
  });

  it("description/input もプロンプト候補として使う", () => {
    const description = buildRemoteMcpParams(
      JSON.stringify({ properties: { description: { type: "string" } }, required: ["description"] }),
      { prompt: "scene" },
    );
    const input = buildRemoteMcpParams(
      JSON.stringify({ properties: { input: { type: "string" } }, required: ["input"] }),
      { prompt: "scene" },
    );
    expect(description.params).toEqual({ description: "scene" });
    expect(input.params).toEqual({ input: "scene" });
  });

  it("未知の required は推測で埋めず、不足項目として返す", () => {
    const result = buildRemoteMcpParams(
      JSON.stringify({
        properties: {
          prompt: { type: "string" },
          seed: { type: "integer" },
          input_image: { type: "string" },
        },
        required: ["prompt", "seed", "input_image"],
      }),
      { prompt: "scene" },
    );
    expect(result.params).toEqual({ prompt: "scene" });
    expect(result.missingRequired).toEqual(["seed", "input_image"]);
  });

  it("required の default と const は schema の明示値を使う", () => {
    const result = buildRemoteMcpParams(
      JSON.stringify({
        properties: {
          prompt: { type: "string" },
          seed: { type: "integer", default: 42 },
          mode: { type: "string", const: "fast" },
        },
        required: ["prompt", "seed", "mode"],
      }),
      { prompt: "scene" },
    );
    expect(result.params).toEqual({ seed: 42, mode: "fast", prompt: "scene" });
    expect(result.missingRequired).toEqual([]);
  });

  it("モデル欄の有無を schema から判定する", () => {
    expect(
      remoteMcpSchemaHasModelField(
        JSON.stringify({ properties: { model_name: { type: "string" } } }),
      ),
    ).toBe(true);
    expect(
      remoteMcpSchemaHasModelField(
        JSON.stringify({ properties: { prompt: { type: "string" } } }),
      ),
    ).toBe(false);
  });

  it("壊れた schema は空で送らずエラーを返す", () => {
    const result = buildRemoteMcpParams("{broken", { prompt: "scene" });
    expect(result.paramsJson).toBe("{}");
    expect(result.params).toEqual({});
    expect(result.schemaError).toContain("読み取れません");
  });
});
